// Auto-generated by lele_compiler
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(unused_mut)]
#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
use lele::tensor::TensorView;
use lele::kernels::*;


#[derive(Default)]
pub struct HiFiGANWorkspace {
    pub buf_0: Vec<f32>,
    pub buf_1: Vec<f32>,
    pub buf_2: Vec<f32>,
    pub buf_3: Vec<f32>,
    pub buf_4: Vec<f32>,
    pub buf_5: Vec<f32>,
    pub buf_6: Vec<f32>,
    pub buf_7: Vec<f32>,
    pub buf_8: Vec<f32>,
    pub buf_9: Vec<f32>,
    pub buf_10: Vec<f32>,
    pub buf_11: Vec<f32>,
}
impl HiFiGANWorkspace {
    pub fn new() -> Self {
        Self::default()
    }
}

pub struct HiFiGAN<'a> {
    data: &'a [u8],
    _phantom: std::marker::PhantomData<&'a ()>,
    #[cfg(target_arch = "aarch64")]
    prepared_weights_cache: std::cell::RefCell<std::collections::HashMap<(usize, usize), std::sync::Arc<lele::kernels::PreparedWeightsArm>>>,
}

impl<'a> HiFiGAN<'a> {
    pub fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            _phantom: std::marker::PhantomData,
            #[cfg(target_arch = "aarch64")]
            prepared_weights_cache: std::cell::RefCell::new(std::collections::HashMap::new()),
        }
    }
fn conv1d_relu<'c, 'd>(
    &self,
    input: lele::tensor::TensorView<'c>,
    weight: lele::tensor::TensorView<'c>,
    bias: Option<&lele::tensor::TensorView<'c>>,
    stride: usize,
    dilation: usize,
    groups: usize,
    padding: usize,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::conv1d_fused(
        &input,
        &weight,
        bias,
        &[dilation as i64],
        groups as i64,
        &[padding as i64, padding as i64],
        &[stride as i64],
        true,
        output_buf,
    )
}
fn layer_norm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    scale: lele::tensor::TensorView<'c>,
    bias: lele::tensor::TensorView<'c>,
    epsilon: lele::tensor::TensorView<'c>,
    _two: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    let eps = epsilon.data.first().cloned().unwrap_or(1e-5);
    lele::kernels::layer_norm(input, &scale, &bias, -1, eps, output_buf)
}
fn linear_quantized<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, false, output_buf,
    )
}

fn linear_quantized_relu<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, true, output_buf,
    )
}

#[cfg(target_arch = "aarch64")]
fn linear_quantized_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        false,
        output_buf,
    )
}

/// ARM-optimized quantized linear + ReLU with pre-packed weights.
/// Uses fused DynQuant+GEMM: eliminates f32 intermediate buffer, per-call u8
/// allocation, and separate f32→u8 conversion pass.
#[cfg(target_arch = "aarch64")]
fn linear_quantized_relu_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        true,
        output_buf,
    )
}

/// ARM-optimized MatMulInteger with pre-packed weight cache.
/// Used for unfused MatMulInteger nodes where B is a static model weight.
/// Eliminates: per-call B packing, B u8→f32→u8 roundtrip, heap alloc.
#[cfg(target_arch = "aarch64")]
fn mat_mul_integer_arm<'c, 'd>(
    &self,
    a: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    a_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    b_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_a = a_zero_point.and_then(|z| z.data.first().cloned());
    let zp_b = b_zero_point.and_then(|z| z.data.first()).map(|&v| v as u8);

    lele::kernels::mat_mul_integer_prepared_arm(a, &pw, zp_a, zp_b, None, None, false, output_buf)
}

// Helper for pre-quantized inputs (used in attention where input is already quantized)
#[inline]
fn linear_quantized_prequant<'c, 'd>(
    &self,
    input_quantized: &lele::tensor::TensorView<'c, f32>,
    input_scale: &lele::tensor::TensorView<'c, f32>,
    input_zero_point: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
    scale_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let combined_scale = lele::kernels::mul(input_scale, &weight_scale, scale_buf);

    // FUSED: MatMul + Scale + Bias in one operation
    lele::kernels::mat_mul_integer_with_scale_bias(
        input_quantized,
        &weight_int8,
        Some(input_zero_point),
        Some(&weight_zero),
        Some(&combined_scale),
        Some(&bias),
        output_buf,
    )
}
fn linear<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    weight: &lele::tensor::TensorView<'c>,
    bias: &lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::matmul_fused_add(input, weight, bias, output_buf)
}

fn embedding_concat<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: f32,
    weight: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    // ConstantOfShape + Concat pattern
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

fn embedding_concat_i64<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: i64,
    weight: lele::tensor::TensorView<'c, i64>,
    output_buf: &'d mut Vec<i64>,
) -> lele::tensor::TensorView<'d, i64> {
    // ConstantOfShape + Concat pattern (i64)
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

    #[inline(never)]
    fn run_chunk_0<'w>(&self, ws: &'w mut HiFiGANWorkspace, f0: TensorView<'w, f32>, mel: TensorView<'w, f32>) -> (TensorView<'static, f32>, TensorView<'static, f32>) {
        let _Transpose_output_0 = lele::kernels::transpose(&mel, &[0, 2, 1], &mut ws.buf_0);
        let _generator_Unsqueeze_output_0 = lele::kernels::unsqueeze(&f0, &[-1]);
        let _generator_Div_output_0 = lele::kernels::div(&_generator_Unsqueeze_output_0, &self.weight_f32(56531232, 4, &[]), &mut ws.buf_2);
        let _generator_Slice_output_0 = lele::kernels::slice(&_generator_Div_output_0, &[1], &[9223372036854775807], &[1], &[1], &mut ws.buf_3);
        let _generator_Slice_1_output_0 = lele::kernels::slice(&_generator_Div_output_0, &[0], &[-1], &[1], &[1], &mut ws.buf_4);
        let _generator_Sub_output_0 = lele::kernels::sub(&_generator_Slice_output_0, &_generator_Slice_1_output_0, &mut ws.buf_5);
        let _generator_Pad_output_0 = lele::kernels::pad(&_generator_Sub_output_0, &[0, 0, 0, 0, 1, 0], None, "constant", &mut ws.buf_6);
        let _generator_Mul_output_0 = lele::kernels::mul(&_generator_Div_output_0, &self.weight_f32(56531312, 256, &[64]), &mut ws.buf_7);
        let _generator_Mul_1_output_0 = lele::kernels::mul(&_generator_Pad_output_0, &self.weight_f32(56531568, 4, &[]), &mut ws.buf_1);
        let _generator_Mul_2_output_0 = lele::kernels::mul(&_generator_Mul_1_output_0, &self.weight_f32(56531312, 256, &[64]), &mut ws.buf_8);
        let _generator_Mul_3_output_0 = lele::kernels::mul(&_generator_Mul_2_output_0, &self.weight_f32(56531584, 256, &[64]), &mut ws.buf_9);
        let _generator_Div_1_output_0 = lele::kernels::div(&_generator_Mul_3_output_0, &self.weight_f32(56531840, 4, &[]), &mut ws.buf_3);
        let _generator_Add_output_0 = lele::kernels::add(&_generator_Mul_output_0, &_generator_Div_1_output_0, &mut ws.buf_4);
        let _generator_Slice_3_output_0 = lele::kernels::slice(&_generator_Add_output_0, &[-1], &[9223372036854775807], &[2], &[1], &mut ws.buf_2);
        let _generator_Add_1_output_0 = lele::kernels::add(&_generator_Slice_3_output_0, &self.weight_f32(56531568, 4, &[]), &mut ws.buf_5);
        let _generator_Mod_output_0 = lele::kernels::mod_f32(&_generator_Add_1_output_0, &self.weight_f32(56531856, 4, &[]), &mut ws.buf_1);
        let _generator_Sub_1_output_0 = lele::kernels::sub(&_generator_Mod_output_0, &self.weight_f32(56531568, 4, &[]), &mut ws.buf_6);
        let _generator_CumSum_output_0 = lele::kernels::cumsum(&_generator_Sub_1_output_0, 1, false, false, &mut ws.buf_8);
        let _generator_Mod_1_output_0 = lele::kernels::mod_f32(&_generator_CumSum_output_0, &self.weight_f32(56531856, 4, &[]), &mut ws.buf_3);
        let _generator_Slice_4_output_0 = lele::kernels::slice(&_generator_Mod_1_output_0, &[0], &[-1], &[1], &[1], &mut ws.buf_7);
        let _generator_Pad_1_output_0 = lele::kernels::pad(&_generator_Slice_4_output_0, &[0, 1, 0, 0, 0, 0], None, "constant", &mut ws.buf_2);
        let _generator_Add_2_output_0 = lele::kernels::add(&_generator_Add_output_0, &_generator_Pad_1_output_0, &mut ws.buf_5);
        let _generator_Reshape_4_output_0 = lele::kernels::reshape(&_generator_Add_2_output_0, &[1, 1, -1]);
        let _generator_Mul_4_output_0 = lele::kernels::mul(&_generator_Reshape_4_output_0, &self.weight_f32(56531888, 4, &[]), &mut ws.buf_1);
        let _generator_Sin_output_0 = lele::kernels::sin(&_generator_Mul_4_output_0, &mut ws.buf_6);
        let _generator_conv_pre_Conv_output_0 = lele::kernels::conv1d(&_Transpose_output_0, &self.weight_f32(2048, 1835008, &[512, 128, 7]), Some(&self.weight_f32(0, 2048, &[512])), &[1], 1, &[3, 3], &[1], &mut ws.buf_3);
        let _generator_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_conv_pre_Conv_output_0, 0.1, &mut ws.buf_7);
        let _generator_ups_0_ConvTranspose_output_0 = lele::kernels::conv_transpose(&_generator_LeakyRelu_output_0, &self.weight_f32(1838080, 8388608, &[512, 256, 16]), Some(&self.weight_f32(1837056, 1024, &[256])), &[1], 1, &[4, 4], &[8], &mut ws.buf_2);
        let _generator_resblocks_0_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_ups_0_ConvTranspose_output_0, 0.1, &mut ws.buf_4);
        let _generator_resblocks_0_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_0_LeakyRelu_output_0, &self.weight_f32(12497856, 786432, &[256, 256, 3]), Some(&self.weight_f32(12496832, 1024, &[256])), &[1], 1, &[1, 1], &[1], &mut ws.buf_5);
        let _generator_resblocks_0_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_0_convs1_0_Conv_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_0_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_0_LeakyRelu_1_output_0, &self.weight_f32(14860224, 786432, &[256, 256, 3]), Some(&self.weight_f32(14859200, 1024, &[256])), &[1], 1, &[1, 1], &[1], &mut ws.buf_0);
        let _generator_resblocks_0_Add_output_0 = lele::kernels::add(&_generator_resblocks_0_convs2_0_Conv_output_0, &_generator_ups_0_ConvTranspose_output_0, &mut ws.buf_3);
        let _generator_resblocks_0_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_0_Add_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_0_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_0_LeakyRelu_2_output_0, &self.weight_f32(13285312, 786432, &[256, 256, 3]), Some(&self.weight_f32(13284288, 1024, &[256])), &[3], 1, &[3, 3], &[1], &mut ws.buf_8);
        let _generator_resblocks_0_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_0_convs1_1_Conv_output_0, 0.1, &mut ws.buf_9);
        let _generator_resblocks_0_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_0_LeakyRelu_3_output_0, &self.weight_f32(15647680, 786432, &[256, 256, 3]), Some(&self.weight_f32(15646656, 1024, &[256])), &[1], 1, &[1, 1], &[1], &mut ws.buf_5);
        let _generator_resblocks_0_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_0_convs2_1_Conv_output_0, &_generator_resblocks_0_Add_output_0, &mut ws.buf_1);
        let _generator_resblocks_0_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_0_Add_1_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_0_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_0_LeakyRelu_4_output_0, &self.weight_f32(14072768, 786432, &[256, 256, 3]), Some(&self.weight_f32(14071744, 1024, &[256])), &[5], 1, &[5, 5], &[1], &mut ws.buf_10);
        let _generator_resblocks_0_LeakyRelu_5_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_0_convs1_2_Conv_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_0_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_0_LeakyRelu_5_output_0, &self.weight_f32(16435136, 786432, &[256, 256, 3]), Some(&self.weight_f32(16434112, 1024, &[256])), &[1], 1, &[1, 1], &[1], &mut ws.buf_8);
        let _generator_resblocks_0_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_0_convs2_2_Conv_output_0, &_generator_resblocks_0_Add_1_output_0, &mut ws.buf_9);
        let _generator_resblocks_1_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_0_LeakyRelu_output_0, &self.weight_f32(17222592, 1835008, &[256, 256, 7]), Some(&self.weight_f32(17221568, 1024, &[256])), &[1], 1, &[3, 3], &[1], &mut ws.buf_3);
        let _generator_resblocks_1_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_1_convs1_0_Conv_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_1_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_1_LeakyRelu_output_0, &self.weight_f32(22730688, 1835008, &[256, 256, 7]), Some(&self.weight_f32(22729664, 1024, &[256])), &[1], 1, &[3, 3], &[1], &mut ws.buf_0);
        let _generator_resblocks_1_Add_output_0 = lele::kernels::add(&_generator_resblocks_1_convs2_0_Conv_output_0, &_generator_ups_0_ConvTranspose_output_0, &mut ws.buf_10);
        let _generator_resblocks_1_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_1_Add_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_1_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_1_LeakyRelu_1_output_0, &self.weight_f32(19058624, 1835008, &[256, 256, 7]), Some(&self.weight_f32(19057600, 1024, &[256])), &[3], 1, &[9, 9], &[1], &mut ws.buf_1);
        let _generator_resblocks_1_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_1_convs1_1_Conv_output_0, 0.1, &mut ws.buf_8);
        let _generator_resblocks_1_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_1_LeakyRelu_2_output_0, &self.weight_f32(24566720, 1835008, &[256, 256, 7]), Some(&self.weight_f32(24565696, 1024, &[256])), &[1], 1, &[3, 3], &[1], &mut ws.buf_3);
        let _generator_resblocks_1_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_1_convs2_1_Conv_output_0, &_generator_resblocks_1_Add_output_0, &mut ws.buf_5);
        let _generator_resblocks_1_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_1_Add_1_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_1_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_1_LeakyRelu_3_output_0, &self.weight_f32(20894656, 1835008, &[256, 256, 7]), Some(&self.weight_f32(20893632, 1024, &[256])), &[5], 1, &[15, 15], &[1], &mut ws.buf_11);
        let _generator_resblocks_1_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_1_convs1_2_Conv_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_1_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_1_LeakyRelu_4_output_0, &self.weight_f32(26402752, 1835008, &[256, 256, 7]), Some(&self.weight_f32(26401728, 1024, &[256])), &[1], 1, &[3, 3], &[1], &mut ws.buf_1);
        let _generator_resblocks_1_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_1_convs2_2_Conv_output_0, &_generator_resblocks_1_Add_1_output_0, &mut ws.buf_8);
        let _generator_Add_3_output_0 = lele::kernels::add(&_generator_resblocks_0_Add_2_output_0, &_generator_resblocks_1_Add_2_output_0, &mut ws.buf_3);
        let _generator_resblocks_2_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_0_LeakyRelu_output_0, &self.weight_f32(28238784, 2883584, &[256, 256, 11]), Some(&self.weight_f32(28237760, 1024, &[256])), &[1], 1, &[5, 5], &[1], &mut ws.buf_10);
        let _generator_resblocks_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_2_convs1_0_Conv_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_2_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_2_LeakyRelu_output_0, &self.weight_f32(36892608, 2883584, &[256, 256, 11]), Some(&self.weight_f32(36891584, 1024, &[256])), &[1], 1, &[5, 5], &[1], &mut ws.buf_11);
        let _generator_resblocks_2_Add_output_0 = lele::kernels::add(&_generator_resblocks_2_convs2_0_Conv_output_0, &_generator_ups_0_ConvTranspose_output_0, &mut ws.buf_7);
        let _generator_resblocks_2_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_2_Add_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_2_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_2_LeakyRelu_1_output_0, &self.weight_f32(31123392, 2883584, &[256, 256, 11]), Some(&self.weight_f32(31122368, 1024, &[256])), &[3], 1, &[15, 15], &[1], &mut ws.buf_5);
        let _generator_resblocks_2_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_2_convs1_1_Conv_output_0, 0.1, &mut ws.buf_4);
        let _generator_resblocks_2_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_2_LeakyRelu_2_output_0, &self.weight_f32(39777216, 2883584, &[256, 256, 11]), Some(&self.weight_f32(39776192, 1024, &[256])), &[1], 1, &[5, 5], &[1], &mut ws.buf_8);
        let _generator_resblocks_2_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_2_convs2_1_Conv_output_0, &_generator_resblocks_2_Add_output_0, &mut ws.buf_0);
        let _generator_resblocks_2_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_2_Add_1_output_0, 0.1, &mut ws.buf_2);
        let _generator_resblocks_2_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_2_LeakyRelu_3_output_0, &self.weight_f32(34008000, 2883584, &[256, 256, 11]), Some(&self.weight_f32(34006976, 1024, &[256])), &[5], 1, &[25, 25], &[1], &mut ws.buf_9);
        let _generator_resblocks_2_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_2_convs1_2_Conv_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_2_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_2_LeakyRelu_4_output_0, &self.weight_f32(42661824, 2883584, &[256, 256, 11]), Some(&self.weight_f32(42660800, 1024, &[256])), &[1], 1, &[5, 5], &[1], &mut ws.buf_5);
        let _generator_resblocks_2_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_2_convs2_2_Conv_output_0, &_generator_resblocks_2_Add_1_output_0, &mut ws.buf_4);
        let _generator_Add_4_output_0 = lele::kernels::add(&_generator_Add_3_output_0, &_generator_resblocks_2_Add_2_output_0, &mut ws.buf_7);
        let _generator_Div_2_output_0 = lele::kernels::div(&_generator_Add_4_output_0, &self.weight_f32(56531904, 4, &[]), &mut ws.buf_8);
        let _generator_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_Div_2_output_0, 0.1, &mut ws.buf_2);
        let _generator_ups_1_ConvTranspose_output_0 = lele::kernels::conv_transpose(&_generator_LeakyRelu_1_output_0, &self.weight_f32(10227200, 2097152, &[256, 128, 16]), Some(&self.weight_f32(10226688, 512, &[128])), &[1], 1, &[4, 4], &[8], &mut ws.buf_9);
        let _generator_source_conv_Conv_output_0 = lele::kernels::conv1d(&_generator_Sin_output_0, &self.weight_f32(56529728, 512, &[128, 1, 1]), Some(&self.weight_f32(56530240, 512, &[128])), &[1], 1, &[0, 0], &[1], &mut ws.buf_1);
        let _generator_Add_5_output_0 = lele::kernels::add(&_generator_ups_1_ConvTranspose_output_0, &_generator_source_conv_Conv_output_0, &mut ws.buf_0);
        let _generator_resblocks_3_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_Add_5_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_3_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_3_LeakyRelu_output_0, &self.weight_f32(45545920, 196608, &[128, 128, 3]), Some(&self.weight_f32(45545408, 512, &[128])), &[1], 1, &[1, 1], &[1], &mut ws.buf_4);
        let _generator_resblocks_3_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_3_convs1_0_Conv_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_3_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_3_LeakyRelu_1_output_0, &self.weight_f32(46137280, 196608, &[128, 128, 3]), Some(&self.weight_f32(46136768, 512, &[128])), &[1], 1, &[1, 1], &[1], &mut ws.buf_2);
        let _generator_resblocks_3_Add_output_0 = lele::kernels::add(&_generator_resblocks_3_convs2_0_Conv_output_0, &_generator_Add_5_output_0, &mut ws.buf_6);
        let _generator_resblocks_3_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_3_Add_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_3_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_3_LeakyRelu_2_output_0, &self.weight_f32(45743040, 196608, &[128, 128, 3]), Some(&self.weight_f32(45742528, 512, &[128])), &[3], 1, &[3, 3], &[1], &mut ws.buf_7);
        let _generator_resblocks_3_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_3_convs1_1_Conv_output_0, 0.1, &mut ws.buf_8);
        let _generator_resblocks_3_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_3_LeakyRelu_3_output_0, &self.weight_f32(46334400, 196608, &[128, 128, 3]), Some(&self.weight_f32(46333888, 512, &[128])), &[1], 1, &[1, 1], &[1], &mut ws.buf_4);
        let _generator_resblocks_3_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_3_convs2_1_Conv_output_0, &_generator_resblocks_3_Add_output_0, &mut ws.buf_5);
        let _generator_resblocks_3_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_3_Add_1_output_0, 0.1, &mut ws.buf_2);
        let _generator_resblocks_3_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_3_LeakyRelu_4_output_0, &self.weight_f32(45940160, 196608, &[128, 128, 3]), Some(&self.weight_f32(45939648, 512, &[128])), &[5], 1, &[5, 5], &[1], &mut ws.buf_9);
        let _generator_resblocks_3_LeakyRelu_5_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_3_convs1_2_Conv_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_3_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_3_LeakyRelu_5_output_0, &self.weight_f32(46531520, 196608, &[128, 128, 3]), Some(&self.weight_f32(46531008, 512, &[128])), &[1], 1, &[1, 1], &[1], &mut ws.buf_7);
        let _generator_resblocks_3_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_3_convs2_2_Conv_output_0, &_generator_resblocks_3_Add_1_output_0, &mut ws.buf_8);
        let _generator_resblocks_4_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_3_LeakyRelu_output_0, &self.weight_f32(46728640, 458752, &[128, 128, 7]), Some(&self.weight_f32(46728128, 512, &[128])), &[1], 1, &[3, 3], &[1], &mut ws.buf_4);
        let _generator_resblocks_4_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_4_convs1_0_Conv_output_0, 0.1, &mut ws.buf_6);
        let _generator_resblocks_4_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_4_LeakyRelu_output_0, &self.weight_f32(48106432, 458752, &[128, 128, 7]), Some(&self.weight_f32(48105920, 512, &[128])), &[1], 1, &[3, 3], &[1], &mut ws.buf_2);
        let _generator_resblocks_4_Add_output_0 = lele::kernels::add(&_generator_resblocks_4_convs2_0_Conv_output_0, &_generator_Add_5_output_0, &mut ws.buf_9);
        let _generator_resblocks_4_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_4_Add_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_4_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_4_LeakyRelu_1_output_0, &self.weight_f32(47187904, 458752, &[128, 128, 7]), Some(&self.weight_f32(47187392, 512, &[128])), &[3], 1, &[9, 9], &[1], &mut ws.buf_5);
        let _generator_resblocks_4_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_4_convs1_1_Conv_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_4_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_4_LeakyRelu_2_output_0, &self.weight_f32(48565696, 458752, &[128, 128, 7]), Some(&self.weight_f32(48565184, 512, &[128])), &[1], 1, &[3, 3], &[1], &mut ws.buf_4);
        let _generator_resblocks_4_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_4_convs2_1_Conv_output_0, &_generator_resblocks_4_Add_output_0, &mut ws.buf_6);
        let _generator_resblocks_4_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_4_Add_1_output_0, 0.1, &mut ws.buf_2);
        let _generator_resblocks_4_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_4_LeakyRelu_3_output_0, &self.weight_f32(47647168, 458752, &[128, 128, 7]), Some(&self.weight_f32(47646656, 512, &[128])), &[5], 1, &[15, 15], &[1], &mut ws.buf_10);
        let _generator_resblocks_4_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_4_convs1_2_Conv_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_4_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_4_LeakyRelu_4_output_0, &self.weight_f32(49024960, 458752, &[128, 128, 7]), Some(&self.weight_f32(49024448, 512, &[128])), &[1], 1, &[3, 3], &[1], &mut ws.buf_5);
        let _generator_resblocks_4_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_4_convs2_2_Conv_output_0, &_generator_resblocks_4_Add_1_output_0, &mut ws.buf_7);
        let _generator_Add_6_output_0 = lele::kernels::add(&_generator_resblocks_3_Add_2_output_0, &_generator_resblocks_4_Add_2_output_0, &mut ws.buf_4);
        let _generator_resblocks_5_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_3_LeakyRelu_output_0, &self.weight_f32(49484224, 720896, &[128, 128, 11]), Some(&self.weight_f32(49483712, 512, &[128])), &[1], 1, &[5, 5], &[1], &mut ws.buf_9);
        let _generator_resblocks_5_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_5_convs1_0_Conv_output_0, 0.1, &mut ws.buf_2);
        let _generator_resblocks_5_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_5_LeakyRelu_output_0, &self.weight_f32(51648448, 720896, &[128, 128, 11]), Some(&self.weight_f32(51647936, 512, &[128])), &[1], 1, &[5, 5], &[1], &mut ws.buf_10);
        let _generator_resblocks_5_Add_output_0 = lele::kernels::add(&_generator_resblocks_5_convs2_0_Conv_output_0, &_generator_Add_5_output_0, &mut ws.buf_1);
        let _generator_resblocks_5_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_5_Add_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_5_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_5_LeakyRelu_1_output_0, &self.weight_f32(50205632, 720896, &[128, 128, 11]), Some(&self.weight_f32(50205120, 512, &[128])), &[3], 1, &[15, 15], &[1], &mut ws.buf_6);
        let _generator_resblocks_5_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_5_convs1_1_Conv_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_5_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_5_LeakyRelu_2_output_0, &self.weight_f32(52369856, 720896, &[128, 128, 11]), Some(&self.weight_f32(52369344, 512, &[128])), &[1], 1, &[5, 5], &[1], &mut ws.buf_7);
        let _generator_resblocks_5_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_5_convs2_1_Conv_output_0, &_generator_resblocks_5_Add_output_0, &mut ws.buf_2);
        let _generator_resblocks_5_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_5_Add_1_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_5_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_5_LeakyRelu_3_output_0, &self.weight_f32(50927040, 720896, &[128, 128, 11]), Some(&self.weight_f32(50926528, 512, &[128])), &[5], 1, &[25, 25], &[1], &mut ws.buf_8);
        let _generator_resblocks_5_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_5_convs1_2_Conv_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_5_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_5_LeakyRelu_4_output_0, &self.weight_f32(53091264, 720896, &[128, 128, 11]), Some(&self.weight_f32(53090752, 512, &[128])), &[1], 1, &[5, 5], &[1], &mut ws.buf_6);
        let _generator_resblocks_5_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_5_convs2_2_Conv_output_0, &_generator_resblocks_5_Add_1_output_0, &mut ws.buf_3);
        let _generator_Add_7_output_0 = lele::kernels::add(&_generator_Add_6_output_0, &_generator_resblocks_5_Add_2_output_0, &mut ws.buf_1);
        let _generator_Div_3_output_0 = lele::kernels::div(&_generator_Add_7_output_0, &self.weight_f32(56531904, 4, &[]), &mut ws.buf_7);
        let _generator_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_Div_3_output_0, 0.1, &mut ws.buf_0);
        let _generator_ups_2_ConvTranspose_output_0 = lele::kernels::conv_transpose(&_generator_LeakyRelu_2_output_0, &self.weight_f32(12324608, 131072, &[128, 64, 4]), Some(&self.weight_f32(12324352, 256, &[64])), &[1], 1, &[1, 1], &[2], &mut ws.buf_8);
        let _generator_resblocks_6_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_ups_2_ConvTranspose_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_6_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_6_LeakyRelu_output_0, &self.weight_f32(53812416, 49152, &[64, 64, 3]), Some(&self.weight_f32(53812160, 256, &[64])), &[1], 1, &[1, 1], &[1], &mut ws.buf_2);
        let _generator_resblocks_6_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_6_convs1_0_Conv_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_6_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_6_LeakyRelu_1_output_0, &self.weight_f32(53960640, 49152, &[64, 64, 3]), Some(&self.weight_f32(53960384, 256, &[64])), &[1], 1, &[1, 1], &[1], &mut ws.buf_1);
        let _generator_resblocks_6_Add_output_0 = lele::kernels::add(&_generator_resblocks_6_convs2_0_Conv_output_0, &_generator_ups_2_ConvTranspose_output_0, &mut ws.buf_4);
        let _generator_resblocks_6_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_6_Add_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_6_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_6_LeakyRelu_2_output_0, &self.weight_f32(53861824, 49152, &[64, 64, 3]), Some(&self.weight_f32(53861568, 256, &[64])), &[3], 1, &[3, 3], &[1], &mut ws.buf_6);
        let _generator_resblocks_6_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_6_convs1_1_Conv_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_6_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_6_LeakyRelu_3_output_0, &self.weight_f32(54010048, 49152, &[64, 64, 3]), Some(&self.weight_f32(54009792, 256, &[64])), &[1], 1, &[1, 1], &[1], &mut ws.buf_2);
        let _generator_resblocks_6_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_6_convs2_1_Conv_output_0, &_generator_resblocks_6_Add_output_0, &mut ws.buf_3);
        let _generator_resblocks_6_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_6_Add_1_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_6_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_6_LeakyRelu_4_output_0, &self.weight_f32(53911232, 49152, &[64, 64, 3]), Some(&self.weight_f32(53910976, 256, &[64])), &[5], 1, &[5, 5], &[1], &mut ws.buf_9);
        let _generator_resblocks_6_LeakyRelu_5_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_6_convs1_2_Conv_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_6_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_6_LeakyRelu_5_output_0, &self.weight_f32(54059456, 49152, &[64, 64, 3]), Some(&self.weight_f32(54059200, 256, &[64])), &[1], 1, &[1, 1], &[1], &mut ws.buf_6);
        let _generator_resblocks_6_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_6_convs2_2_Conv_output_0, &_generator_resblocks_6_Add_1_output_0, &mut ws.buf_7);
        let _generator_resblocks_7_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_6_LeakyRelu_output_0, &self.weight_f32(54108864, 114688, &[64, 64, 7]), Some(&self.weight_f32(54108608, 256, &[64])), &[1], 1, &[3, 3], &[1], &mut ws.buf_2);
        let _generator_resblocks_7_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_7_convs1_0_Conv_output_0, 0.1, &mut ws.buf_4);
        let _generator_resblocks_7_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_7_LeakyRelu_output_0, &self.weight_f32(54453696, 114688, &[64, 64, 7]), Some(&self.weight_f32(54453440, 256, &[64])), &[1], 1, &[3, 3], &[1], &mut ws.buf_1);
        let _generator_resblocks_7_Add_output_0 = lele::kernels::add(&_generator_resblocks_7_convs2_0_Conv_output_0, &_generator_ups_2_ConvTranspose_output_0, &mut ws.buf_9);
        let _generator_resblocks_7_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_7_Add_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_7_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_7_LeakyRelu_1_output_0, &self.weight_f32(54223808, 114688, &[64, 64, 7]), Some(&self.weight_f32(54223552, 256, &[64])), &[3], 1, &[9, 9], &[1], &mut ws.buf_3);
        let _generator_resblocks_7_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_7_convs1_1_Conv_output_0, 0.1, &mut ws.buf_6);
        let _generator_resblocks_7_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_7_LeakyRelu_2_output_0, &self.weight_f32(54568640, 114688, &[64, 64, 7]), Some(&self.weight_f32(54568384, 256, &[64])), &[1], 1, &[3, 3], &[1], &mut ws.buf_2);
        let _generator_resblocks_7_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_7_convs2_1_Conv_output_0, &_generator_resblocks_7_Add_output_0, &mut ws.buf_4);
        let _generator_resblocks_7_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_7_Add_1_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_7_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_7_LeakyRelu_3_output_0, &self.weight_f32(54338752, 114688, &[64, 64, 7]), Some(&self.weight_f32(54338496, 256, &[64])), &[5], 1, &[15, 15], &[1], &mut ws.buf_10);
        let _generator_resblocks_7_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_7_convs1_2_Conv_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_7_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_7_LeakyRelu_4_output_0, &self.weight_f32(54683584, 114688, &[64, 64, 7]), Some(&self.weight_f32(54683328, 256, &[64])), &[1], 1, &[3, 3], &[1], &mut ws.buf_3);
        let _generator_resblocks_7_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_7_convs2_2_Conv_output_0, &_generator_resblocks_7_Add_1_output_0, &mut ws.buf_6);
        let _generator_Add_8_output_0 = lele::kernels::add(&_generator_resblocks_6_Add_2_output_0, &_generator_resblocks_7_Add_2_output_0, &mut ws.buf_2);
        let _generator_resblocks_8_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_6_LeakyRelu_output_0, &self.weight_f32(54798528, 180224, &[64, 64, 11]), Some(&self.weight_f32(54798272, 256, &[64])), &[1], 1, &[5, 5], &[1], &mut ws.buf_9);
        let _generator_resblocks_8_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_8_convs1_0_Conv_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_8_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_8_LeakyRelu_output_0, &self.weight_f32(55339968, 180224, &[64, 64, 11]), Some(&self.weight_f32(55339712, 256, &[64])), &[1], 1, &[5, 5], &[1], &mut ws.buf_10);
        let _generator_resblocks_8_Add_output_0 = lele::kernels::add(&_generator_resblocks_8_convs2_0_Conv_output_0, &_generator_ups_2_ConvTranspose_output_0, &mut ws.buf_0);
        let _generator_resblocks_8_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_8_Add_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_8_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_8_LeakyRelu_1_output_0, &self.weight_f32(54979008, 180224, &[64, 64, 11]), Some(&self.weight_f32(54978752, 256, &[64])), &[3], 1, &[15, 15], &[1], &mut ws.buf_4);
        let _generator_resblocks_8_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_8_convs1_1_Conv_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_8_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_8_LeakyRelu_2_output_0, &self.weight_f32(55520448, 180224, &[64, 64, 11]), Some(&self.weight_f32(55520192, 256, &[64])), &[1], 1, &[5, 5], &[1], &mut ws.buf_6);
        let _generator_resblocks_8_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_8_convs2_1_Conv_output_0, &_generator_resblocks_8_Add_output_0, &mut ws.buf_1);
        let _generator_resblocks_8_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_8_Add_1_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_8_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_8_LeakyRelu_3_output_0, &self.weight_f32(55159488, 180224, &[64, 64, 11]), Some(&self.weight_f32(55159232, 256, &[64])), &[5], 1, &[25, 25], &[1], &mut ws.buf_8);
        let _generator_resblocks_8_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_8_convs1_2_Conv_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_8_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_8_LeakyRelu_4_output_0, &self.weight_f32(55700928, 180224, &[64, 64, 11]), Some(&self.weight_f32(55700672, 256, &[64])), &[1], 1, &[5, 5], &[1], &mut ws.buf_4);
        let _generator_resblocks_8_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_8_convs2_2_Conv_output_0, &_generator_resblocks_8_Add_1_output_0, &mut ws.buf_5);
        let _generator_Add_9_output_0 = lele::kernels::add(&_generator_Add_8_output_0, &_generator_resblocks_8_Add_2_output_0, &mut ws.buf_0);
        let _generator_Div_4_output_0 = lele::kernels::div(&_generator_Add_9_output_0, &self.weight_f32(56531904, 4, &[]), &mut ws.buf_6);
        let _generator_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_Div_4_output_0, 0.1, &mut ws.buf_7);
        let _generator_ups_3_ConvTranspose_output_0 = lele::kernels::conv_transpose(&_generator_LeakyRelu_3_output_0, &self.weight_f32(12455808, 32768, &[64, 32, 4]), Some(&self.weight_f32(12455680, 128, &[32])), &[1], 1, &[1, 1], &[2], &mut ws.buf_8);
        let _generator_resblocks_9_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_ups_3_ConvTranspose_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_9_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_9_LeakyRelu_output_0, &self.weight_f32(55881280, 12288, &[32, 32, 3]), Some(&self.weight_f32(55881152, 128, &[32])), &[1], 1, &[1, 1], &[1], &mut ws.buf_1);
        let _generator_resblocks_9_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_9_convs1_0_Conv_output_0, 0.1, &mut ws.buf_2);
        let _generator_resblocks_9_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_9_LeakyRelu_1_output_0, &self.weight_f32(55918528, 12288, &[32, 32, 3]), Some(&self.weight_f32(55918400, 128, &[32])), &[1], 1, &[1, 1], &[1], &mut ws.buf_0);
        let _generator_resblocks_9_Add_output_0 = lele::kernels::add(&_generator_resblocks_9_convs2_0_Conv_output_0, &_generator_ups_3_ConvTranspose_output_0, &mut ws.buf_4);
        let _generator_resblocks_9_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_9_Add_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_9_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_9_LeakyRelu_2_output_0, &self.weight_f32(55893696, 12288, &[32, 32, 3]), Some(&self.weight_f32(55893568, 128, &[32])), &[3], 1, &[3, 3], &[1], &mut ws.buf_6);
        let _generator_resblocks_9_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_9_convs1_1_Conv_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_9_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_9_LeakyRelu_3_output_0, &self.weight_f32(55930944, 12288, &[32, 32, 3]), Some(&self.weight_f32(55930816, 128, &[32])), &[1], 1, &[1, 1], &[1], &mut ws.buf_1);
        let _generator_resblocks_9_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_9_convs2_1_Conv_output_0, &_generator_resblocks_9_Add_output_0, &mut ws.buf_2);
        let _generator_resblocks_9_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_9_Add_1_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_9_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_9_LeakyRelu_4_output_0, &self.weight_f32(55906112, 12288, &[32, 32, 3]), Some(&self.weight_f32(55905984, 128, &[32])), &[5], 1, &[5, 5], &[1], &mut ws.buf_9);
        let _generator_resblocks_9_LeakyRelu_5_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_9_convs1_2_Conv_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_9_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_9_LeakyRelu_5_output_0, &self.weight_f32(55943360, 12288, &[32, 32, 3]), Some(&self.weight_f32(55943232, 128, &[32])), &[1], 1, &[1, 1], &[1], &mut ws.buf_6);
        let _generator_resblocks_9_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_9_convs2_2_Conv_output_0, &_generator_resblocks_9_Add_1_output_0, &mut ws.buf_7);
        let _generator_resblocks_10_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_9_LeakyRelu_output_0, &self.weight_f32(55955776, 28672, &[32, 32, 7]), Some(&self.weight_f32(55955648, 128, &[32])), &[1], 1, &[3, 3], &[1], &mut ws.buf_1);
        let _generator_resblocks_10_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_10_convs1_0_Conv_output_0, 0.1, &mut ws.buf_4);
        let _generator_resblocks_10_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_10_LeakyRelu_output_0, &self.weight_f32(56042176, 28672, &[32, 32, 7]), Some(&self.weight_f32(56042048, 128, &[32])), &[1], 1, &[3, 3], &[1], &mut ws.buf_0);
        let _generator_resblocks_10_Add_output_0 = lele::kernels::add(&_generator_resblocks_10_convs2_0_Conv_output_0, &_generator_ups_3_ConvTranspose_output_0, &mut ws.buf_9);
        let _generator_resblocks_10_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_10_Add_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_10_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_10_LeakyRelu_1_output_0, &self.weight_f32(55984576, 28672, &[32, 32, 7]), Some(&self.weight_f32(55984448, 128, &[32])), &[3], 1, &[9, 9], &[1], &mut ws.buf_2);
        let _generator_resblocks_10_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_10_convs1_1_Conv_output_0, 0.1, &mut ws.buf_6);
        let _generator_resblocks_10_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_10_LeakyRelu_2_output_0, &self.weight_f32(56070976, 28672, &[32, 32, 7]), Some(&self.weight_f32(56070848, 128, &[32])), &[1], 1, &[3, 3], &[1], &mut ws.buf_1);
        let _generator_resblocks_10_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_10_convs2_1_Conv_output_0, &_generator_resblocks_10_Add_output_0, &mut ws.buf_4);
        let _generator_resblocks_10_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_10_Add_1_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_10_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_10_LeakyRelu_3_output_0, &self.weight_f32(56013376, 28672, &[32, 32, 7]), Some(&self.weight_f32(56013248, 128, &[32])), &[5], 1, &[15, 15], &[1], &mut ws.buf_10);
        let _generator_resblocks_10_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_10_convs1_2_Conv_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_10_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_10_LeakyRelu_4_output_0, &self.weight_f32(56099776, 28672, &[32, 32, 7]), Some(&self.weight_f32(56099648, 128, &[32])), &[1], 1, &[3, 3], &[1], &mut ws.buf_2);
        let _generator_resblocks_10_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_10_convs2_2_Conv_output_0, &_generator_resblocks_10_Add_1_output_0, &mut ws.buf_6);
        let _generator_Add_10_output_0 = lele::kernels::add(&_generator_resblocks_9_Add_2_output_0, &_generator_resblocks_10_Add_2_output_0, &mut ws.buf_1);
        let _generator_resblocks_11_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_9_LeakyRelu_output_0, &self.weight_f32(56128576, 45056, &[32, 32, 11]), Some(&self.weight_f32(56128448, 128, &[32])), &[1], 1, &[5, 5], &[1], &mut ws.buf_9);
        let _generator_resblocks_11_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_11_convs1_0_Conv_output_0, 0.1, &mut ws.buf_0);
        let _generator_resblocks_11_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_11_LeakyRelu_output_0, &self.weight_f32(56264128, 45056, &[32, 32, 11]), Some(&self.weight_f32(56264000, 128, &[32])), &[1], 1, &[5, 5], &[1], &mut ws.buf_10);
        let _generator_resblocks_11_Add_output_0 = lele::kernels::add(&_generator_resblocks_11_convs2_0_Conv_output_0, &_generator_ups_3_ConvTranspose_output_0, &mut ws.buf_5);
        let _generator_resblocks_11_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_11_Add_output_0, 0.1, &mut ws.buf_2);
        let _generator_resblocks_11_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_11_LeakyRelu_1_output_0, &self.weight_f32(56173760, 45056, &[32, 32, 11]), Some(&self.weight_f32(56173632, 128, &[32])), &[3], 1, &[15, 15], &[1], &mut ws.buf_4);
        let _generator_resblocks_11_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_11_convs1_1_Conv_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_11_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_11_LeakyRelu_2_output_0, &self.weight_f32(56309312, 45056, &[32, 32, 11]), Some(&self.weight_f32(56309184, 128, &[32])), &[1], 1, &[5, 5], &[1], &mut ws.buf_6);
        let _generator_resblocks_11_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_11_convs2_1_Conv_output_0, &_generator_resblocks_11_Add_output_0, &mut ws.buf_0);
        let _generator_resblocks_11_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_11_Add_1_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_11_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_11_LeakyRelu_3_output_0, &self.weight_f32(56218944, 45056, &[32, 32, 11]), Some(&self.weight_f32(56218816, 128, &[32])), &[5], 1, &[25, 25], &[1], &mut ws.buf_8);
        let _generator_resblocks_11_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_11_convs1_2_Conv_output_0, 0.1, &mut ws.buf_2);
        let _generator_resblocks_11_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_11_LeakyRelu_4_output_0, &self.weight_f32(56354496, 45056, &[32, 32, 11]), Some(&self.weight_f32(56354368, 128, &[32])), &[1], 1, &[5, 5], &[1], &mut ws.buf_4);
        let _generator_resblocks_11_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_11_convs2_2_Conv_output_0, &_generator_resblocks_11_Add_1_output_0, &mut ws.buf_3);
        let _generator_Add_11_output_0 = lele::kernels::add(&_generator_Add_10_output_0, &_generator_resblocks_11_Add_2_output_0, &mut ws.buf_5);
        let _generator_Div_5_output_0 = lele::kernels::div(&_generator_Add_11_output_0, &self.weight_f32(56531904, 4, &[]), &mut ws.buf_6);
        let _generator_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_Div_5_output_0, 0.1, &mut ws.buf_7);
        let _generator_ups_4_ConvTranspose_output_0 = lele::kernels::conv_transpose(&_generator_LeakyRelu_4_output_0, &self.weight_f32(12488640, 8192, &[32, 16, 4]), Some(&self.weight_f32(12488576, 64, &[16])), &[1], 1, &[1, 1], &[2], &mut ws.buf_8);
        let _generator_resblocks_12_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_ups_4_ConvTranspose_output_0, 0.1, &mut ws.buf_2);
        let _generator_resblocks_12_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_12_LeakyRelu_output_0, &self.weight_f32(56399616, 3072, &[16, 16, 3]), Some(&self.weight_f32(56399552, 64, &[16])), &[1], 1, &[1, 1], &[1], &mut ws.buf_0);
        let _generator_resblocks_12_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_12_convs1_0_Conv_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_12_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_12_LeakyRelu_1_output_0, &self.weight_f32(56409024, 3072, &[16, 16, 3]), Some(&self.weight_f32(56408960, 64, &[16])), &[1], 1, &[1, 1], &[1], &mut ws.buf_3);
        let _generator_resblocks_12_Add_output_0 = lele::kernels::add(&_generator_resblocks_12_convs2_0_Conv_output_0, &_generator_ups_4_ConvTranspose_output_0, &mut ws.buf_4);
        let _generator_resblocks_12_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_12_Add_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_12_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_12_LeakyRelu_2_output_0, &self.weight_f32(56402752, 3072, &[16, 16, 3]), Some(&self.weight_f32(56402688, 64, &[16])), &[3], 1, &[3, 3], &[1], &mut ws.buf_6);
        let _generator_resblocks_12_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_12_convs1_1_Conv_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_12_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_12_LeakyRelu_3_output_0, &self.weight_f32(56412160, 3072, &[16, 16, 3]), Some(&self.weight_f32(56412096, 64, &[16])), &[1], 1, &[1, 1], &[1], &mut ws.buf_0);
        let _generator_resblocks_12_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_12_convs2_1_Conv_output_0, &_generator_resblocks_12_Add_output_0, &mut ws.buf_1);
        let _generator_resblocks_12_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_12_Add_1_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_12_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_12_LeakyRelu_4_output_0, &self.weight_f32(56405888, 3072, &[16, 16, 3]), Some(&self.weight_f32(56405824, 64, &[16])), &[5], 1, &[5, 5], &[1], &mut ws.buf_9);
        let _generator_resblocks_12_LeakyRelu_5_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_12_convs1_2_Conv_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_12_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_12_LeakyRelu_5_output_0, &self.weight_f32(56415296, 3072, &[16, 16, 3]), Some(&self.weight_f32(56415232, 64, &[16])), &[1], 1, &[1, 1], &[1], &mut ws.buf_6);
        let _generator_resblocks_12_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_12_convs2_2_Conv_output_0, &_generator_resblocks_12_Add_1_output_0, &mut ws.buf_7);
        let _generator_resblocks_13_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_12_LeakyRelu_output_0, &self.weight_f32(56418432, 7168, &[16, 16, 7]), Some(&self.weight_f32(56418368, 64, &[16])), &[1], 1, &[3, 3], &[1], &mut ws.buf_0);
        let _generator_resblocks_13_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_13_convs1_0_Conv_output_0, 0.1, &mut ws.buf_4);
        let _generator_resblocks_13_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_13_LeakyRelu_output_0, &self.weight_f32(56440128, 7168, &[16, 16, 7]), Some(&self.weight_f32(56440064, 64, &[16])), &[1], 1, &[3, 3], &[1], &mut ws.buf_3);
        let _generator_resblocks_13_Add_output_0 = lele::kernels::add(&_generator_resblocks_13_convs2_0_Conv_output_0, &_generator_ups_4_ConvTranspose_output_0, &mut ws.buf_9);
        let _generator_resblocks_13_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_13_Add_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_13_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_13_LeakyRelu_1_output_0, &self.weight_f32(56425664, 7168, &[16, 16, 7]), Some(&self.weight_f32(56425600, 64, &[16])), &[3], 1, &[9, 9], &[1], &mut ws.buf_1);
        let _generator_resblocks_13_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_13_convs1_1_Conv_output_0, 0.1, &mut ws.buf_6);
        let _generator_resblocks_13_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_13_LeakyRelu_2_output_0, &self.weight_f32(56447360, 7168, &[16, 16, 7]), Some(&self.weight_f32(56447296, 64, &[16])), &[1], 1, &[3, 3], &[1], &mut ws.buf_0);
        let _generator_resblocks_13_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_13_convs2_1_Conv_output_0, &_generator_resblocks_13_Add_output_0, &mut ws.buf_4);
        let _generator_resblocks_13_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_13_Add_1_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_13_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_13_LeakyRelu_3_output_0, &self.weight_f32(56432896, 7168, &[16, 16, 7]), Some(&self.weight_f32(56432832, 64, &[16])), &[5], 1, &[15, 15], &[1], &mut ws.buf_10);
        let _generator_resblocks_13_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_13_convs1_2_Conv_output_0, 0.1, &mut ws.buf_5);
        let _generator_resblocks_13_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_13_LeakyRelu_4_output_0, &self.weight_f32(56454592, 7168, &[16, 16, 7]), Some(&self.weight_f32(56454528, 64, &[16])), &[1], 1, &[3, 3], &[1], &mut ws.buf_1);
        let _generator_resblocks_13_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_13_convs2_2_Conv_output_0, &_generator_resblocks_13_Add_1_output_0, &mut ws.buf_6);
        let _generator_Add_12_output_0 = lele::kernels::add(&_generator_resblocks_12_Add_2_output_0, &_generator_resblocks_13_Add_2_output_0, &mut ws.buf_0);
        let _generator_resblocks_14_convs1_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_12_LeakyRelu_output_0, &self.weight_f32(56461824, 11264, &[16, 16, 11]), Some(&self.weight_f32(56461760, 64, &[16])), &[1], 1, &[5, 5], &[1], &mut ws.buf_9);
        let _generator_resblocks_14_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_14_convs1_0_Conv_output_0, 0.1, &mut ws.buf_3);
        let _generator_resblocks_14_convs2_0_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_14_LeakyRelu_output_0, &self.weight_f32(56495808, 11264, &[16, 16, 11]), Some(&self.weight_f32(56495744, 64, &[16])), &[1], 1, &[5, 5], &[1], &mut ws.buf_10);
        let _generator_resblocks_14_Add_output_0 = lele::kernels::add(&_generator_resblocks_14_convs2_0_Conv_output_0, &_generator_ups_4_ConvTranspose_output_0, &mut ws.buf_5);
        let _generator_resblocks_14_LeakyRelu_1_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_14_Add_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_14_convs1_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_14_LeakyRelu_1_output_0, &self.weight_f32(56473152, 11264, &[16, 16, 11]), Some(&self.weight_f32(56473088, 64, &[16])), &[3], 1, &[15, 15], &[1], &mut ws.buf_4);
        let _generator_resblocks_14_LeakyRelu_2_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_14_convs1_1_Conv_output_0, 0.1, &mut ws.buf_2);
        let _generator_resblocks_14_convs2_1_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_14_LeakyRelu_2_output_0, &self.weight_f32(56507136, 11264, &[16, 16, 11]), Some(&self.weight_f32(56507072, 64, &[16])), &[1], 1, &[5, 5], &[1], &mut ws.buf_6);
        let _generator_resblocks_14_Add_1_output_0 = lele::kernels::add(&_generator_resblocks_14_convs2_1_Conv_output_0, &_generator_resblocks_14_Add_output_0, &mut ws.buf_3);
        let _generator_resblocks_14_LeakyRelu_3_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_14_Add_1_output_0, 0.1, &mut ws.buf_7);
        let _generator_resblocks_14_convs1_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_14_LeakyRelu_3_output_0, &self.weight_f32(56484480, 11264, &[16, 16, 11]), Some(&self.weight_f32(56484416, 64, &[16])), &[5], 1, &[25, 25], &[1], &mut ws.buf_8);
        let _generator_resblocks_14_LeakyRelu_4_output_0 = lele::kernels::leaky_relu(&_generator_resblocks_14_convs1_2_Conv_output_0, 0.1, &mut ws.buf_1);
        let _generator_resblocks_14_convs2_2_Conv_output_0 = lele::kernels::conv1d(&_generator_resblocks_14_LeakyRelu_4_output_0, &self.weight_f32(56518464, 11264, &[16, 16, 11]), Some(&self.weight_f32(56518400, 64, &[16])), &[1], 1, &[5, 5], &[1], &mut ws.buf_4);
        let _generator_resblocks_14_Add_2_output_0 = lele::kernels::add(&_generator_resblocks_14_convs2_2_Conv_output_0, &_generator_resblocks_14_Add_1_output_0, &mut ws.buf_2);
        let _generator_Add_13_output_0 = lele::kernels::add(&_generator_Add_12_output_0, &_generator_resblocks_14_Add_2_output_0, &mut ws.buf_5);
        let _generator_Div_6_output_0 = lele::kernels::div(&_generator_Add_13_output_0, &self.weight_f32(56531904, 4, &[]), &mut ws.buf_6);
        let _generator_LeakyRelu_5_output_0 = lele::kernels::leaky_relu(&_generator_Div_6_output_0, 0.01, &mut ws.buf_7);
        let _generator_conv_post_Conv_output_0 = lele::kernels::conv1d(&_generator_LeakyRelu_5_output_0, &self.weight_f32(56530768, 448, &[1, 16, 7]), Some(&self.weight_f32(56530752, 4, &[1])), &[1], 1, &[3, 3], &[1], &mut ws.buf_8);
        let _generator_Tanh_output_0 = lele::kernels::tanh_kernel(&_generator_conv_post_Conv_output_0, &mut ws.buf_1);
        let waveform = lele::kernels::squeeze(&_generator_Tanh_output_0, Some(&[1]));
        (unsafe { _generator_Tanh_output_0.detach_or_own() }, unsafe { waveform.detach_or_own() })
    }


    #[cfg(target_arch = "aarch64")]
    fn get_prepared_weight(&self, offset: usize, len: usize, k: usize, n: usize) -> std::sync::Arc<lele::kernels::PreparedWeightsArm> {
        let key = (offset, len);
        {
            let cache = self.prepared_weights_cache.borrow();
            if let Some(pw) = cache.get(&key) {
                return pw.clone();
            }
        }
        let raw_bytes = &self.data[offset..offset+len];
        let pw = std::sync::Arc::new(lele::kernels::prepare_weights_arm(raw_bytes, k, n));
        self.prepared_weights_cache.borrow_mut().insert(key, pw.clone());
        pw
    }
    pub fn weight_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'a, f32> {
        TensorView::from_bytes_f32(&self.data[offset..offset+len], shape)
    }
    pub fn weight_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i32_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i32_as_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i32> {
        TensorView::from_bytes_i32(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i64_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i64_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i32_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i32_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_u8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_u8(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i8(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_f16(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_f16(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_u8_raw(&self, offset: usize, len: usize) -> &'a [u8] {
        &self.data[offset..offset+len]
    }

    // Inference Entry Point
    pub fn forward(&self, mel: TensorView<'a>, f0: TensorView<'a>) -> TensorView<'static> {
        let mut ws = HiFiGANWorkspace::new();
        let res = self.forward_with_workspace(&mut ws, mel, f0);
        res.to_owned()
    }
    pub fn forward_with_workspace<'w>(&self, ws: &'w mut HiFiGANWorkspace, mel: TensorView<'w>, f0: TensorView<'w>) -> TensorView<'w> {
        let (_generator_Tanh_output_0, waveform) = self.run_chunk_0(ws, f0, mel);
        waveform
    }
}
