// Auto-generated by lele_compiler
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(unused_mut)]
#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
use lele::tensor::TensorView;
use lele::kernels::*;


#[derive(Default)]
pub struct HNSEPWorkspace {
    pub buf_0: Vec<f32>,
    pub buf_1: Vec<f32>,
    pub buf_2: Vec<f32>,
    pub buf_3: Vec<f32>,
    pub buf_4: Vec<f32>,
    pub buf_5: Vec<f32>,
    pub buf_6: Vec<f32>,
    pub buf_7: Vec<f32>,
    pub buf_8: Vec<f32>,
    pub buf_9: Vec<f32>,
    pub buf_10: Vec<f32>,
    pub buf_11: Vec<f32>,
    pub buf_12: Vec<f32>,
    pub buf_13: Vec<f32>,
    pub buf_14: Vec<f32>,
    pub buf_15: Vec<f32>,
    pub buf_16: Vec<f32>,
    pub buf_17: Vec<f32>,
    pub buf_18: Vec<f32>,
    pub buf_19: Vec<f32>,
    pub buf_20: Vec<f32>,
    pub buf_21: Vec<f32>,
    pub buf_22: Vec<f32>,
    pub buf_23: Vec<f32>,
    pub buf_24: Vec<f32>,
    pub buf_25: Vec<f32>,
    pub buf_26: Vec<f32>,
    pub buf_27: Vec<f32>,
    pub buf_28: Vec<f32>,
    pub buf_29: Vec<f32>,
}
impl HNSEPWorkspace {
    pub fn new() -> Self {
        Self::default()
    }
}

pub struct HNSEP<'a> {
    data: &'a [u8],
    _phantom: std::marker::PhantomData<&'a ()>,
    #[cfg(target_arch = "aarch64")]
    prepared_weights_cache: std::cell::RefCell<std::collections::HashMap<(usize, usize), std::sync::Arc<lele::kernels::PreparedWeightsArm>>>,
}

impl<'a> HNSEP<'a> {
    pub fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            _phantom: std::marker::PhantomData,
            #[cfg(target_arch = "aarch64")]
            prepared_weights_cache: std::cell::RefCell::new(std::collections::HashMap::new()),
        }
    }
fn conv1d_relu<'c, 'd>(
    &self,
    input: lele::tensor::TensorView<'c>,
    weight: lele::tensor::TensorView<'c>,
    bias: Option<&lele::tensor::TensorView<'c>>,
    stride: usize,
    dilation: usize,
    groups: usize,
    padding: usize,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::conv1d_fused(
        &input,
        &weight,
        bias,
        &[dilation as i64],
        groups as i64,
        &[padding as i64, padding as i64],
        &[stride as i64],
        true,
        output_buf,
    )
}
fn layer_norm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    scale: lele::tensor::TensorView<'c>,
    bias: lele::tensor::TensorView<'c>,
    epsilon: lele::tensor::TensorView<'c>,
    _two: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    let eps = epsilon.data.first().cloned().unwrap_or(1e-5);
    lele::kernels::layer_norm(input, &scale, &bias, -1, eps, output_buf)
}
fn linear_quantized<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, false, output_buf,
    )
}

fn linear_quantized_relu<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, true, output_buf,
    )
}

#[cfg(target_arch = "aarch64")]
fn linear_quantized_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        false,
        output_buf,
    )
}

/// ARM-optimized quantized linear + ReLU with pre-packed weights.
/// Uses fused DynQuant+GEMM: eliminates f32 intermediate buffer, per-call u8
/// allocation, and separate f32→u8 conversion pass.
#[cfg(target_arch = "aarch64")]
fn linear_quantized_relu_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        true,
        output_buf,
    )
}

/// ARM-optimized MatMulInteger with pre-packed weight cache.
/// Used for unfused MatMulInteger nodes where B is a static model weight.
/// Eliminates: per-call B packing, B u8→f32→u8 roundtrip, heap alloc.
#[cfg(target_arch = "aarch64")]
fn mat_mul_integer_arm<'c, 'd>(
    &self,
    a: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    a_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    b_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_a = a_zero_point.and_then(|z| z.data.first().cloned());
    let zp_b = b_zero_point.and_then(|z| z.data.first()).map(|&v| v as u8);

    lele::kernels::mat_mul_integer_prepared_arm(a, &pw, zp_a, zp_b, None, None, false, output_buf)
}

// Helper for pre-quantized inputs (used in attention where input is already quantized)
#[inline]
fn linear_quantized_prequant<'c, 'd>(
    &self,
    input_quantized: &lele::tensor::TensorView<'c, f32>,
    input_scale: &lele::tensor::TensorView<'c, f32>,
    input_zero_point: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
    scale_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let combined_scale = lele::kernels::mul(input_scale, &weight_scale, scale_buf);

    // FUSED: MatMul + Scale + Bias in one operation
    lele::kernels::mat_mul_integer_with_scale_bias(
        input_quantized,
        &weight_int8,
        Some(input_zero_point),
        Some(&weight_zero),
        Some(&combined_scale),
        Some(&bias),
        output_buf,
    )
}
fn linear<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    weight: &lele::tensor::TensorView<'c>,
    bias: &lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::matmul_fused_add(input, weight, bias, output_buf)
}

fn embedding_concat<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: f32,
    weight: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    // ConstantOfShape + Concat pattern
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

fn embedding_concat_i64<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: i64,
    weight: lele::tensor::TensorView<'c, i64>,
    output_buf: &'d mut Vec<i64>,
) -> lele::tensor::TensorView<'d, i64> {
    // ConstantOfShape + Concat pattern (i64)
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

    #[inline(never)]
    fn run_chunk_0<'w>(&self, ws: &'w mut HNSEPWorkspace, _stg1_low_band_net_dec4_Constant_1_output_0: TensorView<'w, f32>, input: TensorView<'w, f32>) -> TensorView<'static, f32> {
        let _Slice_output_0 = lele::kernels::slice(&input, &[0], &[1024], &[2], &[1], &mut ws.buf_0);
        let _Slice_1_output_0 = lele::kernels::slice(&_Slice_output_0, &[0], &[512], &[2], &[1], &mut ws.buf_1);
        let _Slice_2_output_0 = lele::kernels::slice(&_Slice_output_0, &[512], &[9223372036854775807], &[2], &[1], &mut ws.buf_2);
        let _stg1_low_band_net_enc1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_Slice_1_output_0, &self.weight_f32(96, 1152, &[16, 2, 3, 3]), Some(&self.weight_f32(1248, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _enc1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_Slice_2_output_0, &self.weight_f32(1312, 576, &[8, 2, 3, 3]), Some(&self.weight_f32(1888, 32, &[8])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _stg1_low_band_net_enc1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_enc1_conv_conv_0_Conv_output_0, &mut ws.buf_5);
        let _enc1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_enc1_conv_conv_0_Conv_output_0, &mut ws.buf_6);
        let _stg1_low_band_net_enc2_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc1_conv_conv_2_Relu_output_0, &self.weight_f32(1920, 18432, &[32, 16, 3, 3]), Some(&self.weight_f32(20352, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_7);
        let _enc2_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc1_conv_conv_2_Relu_output_0, &self.weight_f32(20480, 4608, &[16, 8, 3, 3]), Some(&self.weight_f32(25088, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_8);
        let _stg1_low_band_net_enc2_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg1_low_band_net_enc2_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_9);
        let _enc2_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc2_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_10);
        let _stg1_low_band_net_enc2_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc2_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(25152, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(62016, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _enc2_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc2_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(62144, 9216, &[16, 16, 3, 3]), Some(&self.weight_f32(71360, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _stg1_low_band_net_enc2_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg1_low_band_net_enc2_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_11);
        let _enc2_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc2_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_12);
        let _stg1_low_band_net_enc3_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc2_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(71424, 73728, &[64, 32, 3, 3]), Some(&self.weight_f32(145152, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_7);
        let _enc3_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc2_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(145408, 18432, &[32, 16, 3, 3]), Some(&self.weight_f32(163840, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_8);
        let _stg1_low_band_net_enc3_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg1_low_band_net_enc3_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_9);
        let _enc3_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc3_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_10);
        let _stg1_low_band_net_enc3_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc3_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(163968, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(311424, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _enc3_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc3_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(311680, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(348544, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _stg1_low_band_net_enc3_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg1_low_band_net_enc3_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_13);
        let _enc3_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc3_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_14);
        let _stg1_low_band_net_enc4_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc3_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(348672, 221184, &[96, 64, 3, 3]), Some(&self.weight_f32(569856, 384, &[96])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_7);
        let _enc4_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc3_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(570240, 55296, &[48, 32, 3, 3]), Some(&self.weight_f32(625536, 192, &[48])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_8);
        let _stg1_low_band_net_enc4_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg1_low_band_net_enc4_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_9);
        let _enc4_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc4_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_10);
        let _stg1_low_band_net_enc4_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc4_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(625728, 331776, &[96, 96, 3, 3]), Some(&self.weight_f32(957504, 384, &[96])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _enc4_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc4_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(957888, 82944, &[48, 48, 3, 3]), Some(&self.weight_f32(1040832, 192, &[48])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _stg1_low_band_net_enc4_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg1_low_band_net_enc4_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_15);
        let _enc4_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc4_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_16);
        let _stg1_low_band_net_enc5_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc4_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(1041024, 442368, &[128, 96, 3, 3]), Some(&self.weight_f32(1483392, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_7);
        let _enc5_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc4_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(1483904, 110592, &[64, 48, 3, 3]), Some(&self.weight_f32(1594496, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_8);
        let _stg1_low_band_net_enc5_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg1_low_band_net_enc5_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_9);
        let _enc5_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc5_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_10);
        let _stg1_low_band_net_enc5_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc5_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(1594752, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(2184576, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _enc5_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(2185088, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(2332544, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _stg1_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg1_low_band_net_enc5_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_17);
        let _enc5_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc5_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_18);
        let _stg1_low_band_net_aspp_conv1_conv1_0_ReduceMean_output_0 = lele::kernels::reduce_mean(&_stg1_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &[-2], true, &mut ws.buf_7);
        let _stg1_low_band_net_aspp_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(2332800, 65536, &[128, 128, 1, 1]), Some(&self.weight_f32(2398336, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let _stg1_low_band_net_aspp_conv3_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(2398848, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(2988672, 512, &[128])), &[4, 2], 1, &[4, 2, 4, 2], &[1, 1], &mut ws.buf_9);
        let _stg1_low_band_net_aspp_conv4_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(2989184, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(3579008, 512, &[128])), &[8, 4], 1, &[8, 4, 8, 4], &[1, 1], &mut ws.buf_10);
        let _stg1_low_band_net_aspp_conv5_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(3579520, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(4169344, 512, &[128])), &[12, 6], 1, &[12, 6, 12, 6], &[1, 1], &mut ws.buf_3);
        let _aspp_conv1_conv1_0_ReduceMean_output_0 = lele::kernels::reduce_mean(&_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &[-2], true, &mut ws.buf_4);
        let _aspp_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(4169856, 16384, &[64, 64, 1, 1]), Some(&self.weight_f32(4186240, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_19);
        let _aspp_conv3_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(4186496, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(4333952, 256, &[64])), &[4, 2], 1, &[4, 2, 4, 2], &[1, 1], &mut ws.buf_20);
        let _aspp_conv4_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(4334208, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(4481664, 256, &[64])), &[8, 4], 1, &[8, 4, 8, 4], &[1, 1], &mut ws.buf_21);
        let _aspp_conv5_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(4481920, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(4629376, 256, &[64])), &[12, 6], 1, &[12, 6, 12, 6], &[1, 1], &mut ws.buf_22);
        let _stg1_low_band_net_aspp_conv1_conv1_1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_aspp_conv1_conv1_0_ReduceMean_output_0, &self.weight_f32(4629632, 65536, &[128, 128, 1, 1]), Some(&self.weight_f32(4695168, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_17);
        let _stg1_low_band_net_aspp_conv2_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_aspp_conv2_conv_conv_0_Conv_output_0, &mut ws.buf_23);
        let _stg1_low_band_net_aspp_conv3_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_aspp_conv3_conv_conv_0_Conv_output_0, &mut ws.buf_24);
        let _stg1_low_band_net_aspp_conv4_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_aspp_conv4_conv_conv_0_Conv_output_0, &mut ws.buf_25);
        let _stg1_low_band_net_aspp_conv5_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_aspp_conv5_conv_conv_0_Conv_output_0, &mut ws.buf_26);
        let _aspp_conv1_conv1_1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_aspp_conv1_conv1_0_ReduceMean_output_0, &self.weight_f32(4695680, 16384, &[64, 64, 1, 1]), Some(&self.weight_f32(4712064, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_18);
        let _aspp_conv2_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv2_conv_conv_0_Conv_output_0, &mut ws.buf_7);
        let _aspp_conv3_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv3_conv_conv_0_Conv_output_0, &mut ws.buf_8);
        let _aspp_conv4_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv4_conv_conv_0_Conv_output_0, &mut ws.buf_9);
        let _aspp_conv5_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv5_conv_conv_0_Conv_output_0, &mut ws.buf_10);
        let _stg1_low_band_net_aspp_Expand_output_0 = lele::kernels::relu(&_stg1_low_band_net_aspp_conv1_conv1_1_conv_conv_0_Conv_output_0, &mut ws.buf_3);
        let _aspp_conv1_conv1_1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv1_conv1_1_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _stg1_low_band_net_aspp_Tile_output_0 = lele::kernels::tile(&_stg1_low_band_net_aspp_Expand_output_0, &[1, 1, 32, 1], &mut ws.buf_19);
        let _aspp_Tile_output_0 = lele::kernels::tile(&_aspp_conv1_conv1_1_conv_conv_2_Relu_output_0, &[1, 1, 32, 1], &mut ws.buf_20);
        let _stg1_low_band_net_aspp_Concat_2_output_0 = lele::kernels::concat(&[&_stg1_low_band_net_aspp_Tile_output_0, &_stg1_low_band_net_aspp_conv2_conv_conv_2_Relu_output_0, &_stg1_low_band_net_aspp_conv3_conv_conv_2_Relu_output_0, &_stg1_low_band_net_aspp_conv4_conv_conv_2_Relu_output_0, &_stg1_low_band_net_aspp_conv5_conv_conv_2_Relu_output_0], 1, &mut ws.buf_21);
        let _aspp_Concat_2_output_0 = lele::kernels::concat(&[&_aspp_Tile_output_0, &_aspp_conv2_conv_conv_2_Relu_output_0, &_aspp_conv3_conv_conv_2_Relu_output_0, &_aspp_conv4_conv_conv_2_Relu_output_0, &_aspp_conv5_conv_conv_2_Relu_output_0], 1, &mut ws.buf_22);
        let _stg1_low_band_net_aspp_bottleneck_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_aspp_Concat_2_output_0, &self.weight_f32(4712352, 327680, &[128, 640, 1, 1]), Some(&self.weight_f32(5040032, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_17);
        let _aspp_bottleneck_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_aspp_Concat_2_output_0, &self.weight_f32(5040544, 81920, &[64, 320, 1, 1]), Some(&self.weight_f32(5122464, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_18);
        let _stg1_low_band_net_aspp_bottleneck_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_aspp_bottleneck_conv_conv_0_Conv_output_0, &mut ws.buf_3);
        let _aspp_bottleneck_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_aspp_bottleneck_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _stg1_low_band_net_dec4_Resize_output_0 = lele::kernels::resize_nearest(&_stg1_low_band_net_aspp_bottleneck_conv_conv_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_19);
        let _dec4_Resize_output_0 = lele::kernels::resize_nearest(&_aspp_bottleneck_conv_conv_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_7);
        let _stg1_low_band_net_dec4_Concat_output_0 = lele::kernels::concat(&[&_stg1_low_band_net_dec4_Resize_output_0, &_stg1_low_band_net_enc4_conv2_conv_conv_2_LeakyRelu_output_0], 1, &mut ws.buf_8);
        let _dec4_Concat_output_0 = lele::kernels::concat(&[&_dec4_Resize_output_0, &_enc4_conv2_conv_conv_2_LeakyRelu_output_0], 1, &mut ws.buf_9);
        let _stg1_low_band_net_dec4_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_dec4_Concat_output_0, &self.weight_f32(5122736, 774144, &[96, 224, 3, 3]), Some(&self.weight_f32(5896880, 384, &[96])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_10);
        let _dec4_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_dec4_Concat_output_0, &self.weight_f32(5897264, 193536, &[48, 112, 3, 3]), Some(&self.weight_f32(6090800, 192, &[48])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_17);
        let _stg1_low_band_net_dec4_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_dec4_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_3);
        let _dec4_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_dec4_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _stg1_low_band_net_dec3_Resize_output_0 = lele::kernels::resize_nearest(&_stg1_low_band_net_dec4_conv1_conv_conv_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_15);
        let _dec3_Resize_output_0 = lele::kernels::resize_nearest(&_dec4_conv1_conv_conv_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_7);
        let _stg1_low_band_net_dec3_Concat_output_0 = lele::kernels::concat(&[&_stg1_low_band_net_dec3_Resize_output_0, &_stg1_low_band_net_enc3_conv2_conv_conv_2_LeakyRelu_output_0], 1, &mut ws.buf_8);
        let _dec3_Concat_output_0 = lele::kernels::concat(&[&_dec3_Resize_output_0, &_enc3_conv2_conv_conv_2_LeakyRelu_output_0], 1, &mut ws.buf_9);
        let _stg1_low_band_net_dec3_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_dec3_Concat_output_0, &self.weight_f32(6090992, 368640, &[64, 160, 3, 3]), Some(&self.weight_f32(6459632, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_10);
        let _dec3_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_dec3_Concat_output_0, &self.weight_f32(6459888, 92160, &[32, 80, 3, 3]), Some(&self.weight_f32(6552048, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_16);
        let _stg1_low_band_net_dec3_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_dec3_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_3);
        let _dec3_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_dec3_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _stg1_low_band_net_dec2_Resize_output_0 = lele::kernels::resize_nearest(&_stg1_low_band_net_dec3_conv1_conv_conv_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_13);
        let _dec2_Resize_output_0 = lele::kernels::resize_nearest(&_dec3_conv1_conv_conv_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_7);
        let _stg1_low_band_net_dec2_Concat_output_0 = lele::kernels::concat(&[&_stg1_low_band_net_dec2_Resize_output_0, &_stg1_low_band_net_enc2_conv2_conv_conv_2_LeakyRelu_output_0], 1, &mut ws.buf_8);
        let _dec2_Concat_output_0 = lele::kernels::concat(&[&_dec2_Resize_output_0, &_enc2_conv2_conv_conv_2_LeakyRelu_output_0], 1, &mut ws.buf_9);
        let _stg1_low_band_net_dec2_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_dec2_Concat_output_0, &self.weight_f32(6552176, 110592, &[32, 96, 3, 3]), Some(&self.weight_f32(6662768, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_10);
        let _dec2_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_dec2_Concat_output_0, &self.weight_f32(6662896, 27648, &[16, 48, 3, 3]), Some(&self.weight_f32(6690544, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_14);
        let _stg1_low_band_net_dec2_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_dec2_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_3);
        let _dec2_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_dec2_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _stg1_low_band_net_lstm_dec2_conv_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_dec2_conv1_conv_conv_2_Relu_output_0, &self.weight_f32(6690608, 128, &[1, 32, 1, 1]), Some(&self.weight_f32(6690736, 4, &[1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_11);
        let _lstm_dec2_conv_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_dec2_conv1_conv_conv_2_Relu_output_0, &self.weight_f32(6690752, 64, &[1, 16, 1, 1]), Some(&self.weight_f32(6690816, 4, &[1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let _stg1_low_band_net_lstm_dec2_conv_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_lstm_dec2_conv_conv_conv_0_Conv_output_0, &mut ws.buf_8);
        let _lstm_dec2_conv_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_lstm_dec2_conv_conv_conv_0_Conv_output_0, &mut ws.buf_9);
        let _stg1_low_band_net_lstm_dec2_Gather_3_output_0 = lele::kernels::gather(&_stg1_low_band_net_lstm_dec2_conv_conv_conv_2_Relu_output_0, &self.weight_i64(0, 8, &[]), 1, &mut ws.buf_10);
        let _lstm_dec2_Gather_3_output_0 = lele::kernels::gather(&_lstm_dec2_conv_conv_conv_2_Relu_output_0, &self.weight_i64(0, 8, &[]), 1, &mut ws.buf_12);
        let _stg1_low_band_net_lstm_dec2_Transpose_output_0 = lele::kernels::transpose(&_stg1_low_band_net_lstm_dec2_Gather_3_output_0, &[2, 0, 1], &mut ws.buf_13);
        let _lstm_dec2_Transpose_output_0 = lele::kernels::transpose(&_lstm_dec2_Gather_3_output_0, &[2, 0, 1], &mut ws.buf_14);
        let mut buf__stg1_low_band_net_lstm_dec2_lstm_LSTM_output_0_h = Vec::<f32>::new();
        let mut buf__stg1_low_band_net_lstm_dec2_lstm_LSTM_output_0_c = Vec::<f32>::new();
        let (_stg1_low_band_net_lstm_dec2_lstm_LSTM_output_0, _stg1_low_band_net_lstm_dec2_lstm_LSTM_output_1, _stg1_low_band_net_lstm_dec2_lstm_LSTM_output_2) = lele::kernels::lstm(&_stg1_low_band_net_lstm_dec2_Transpose_output_0, &self.weight_f32(6690832, 524288, &[2, 256, 256]), &self.weight_f32(7215120, 131072, &[2, 256, 64]), Some(&self.weight_f32(7346192, 4096, &[2, 512])), None, Some(&self.weight_f32(7350288, 512, &[2, 1, 64])), Some(&self.weight_f32(7350288, 512, &[2, 1, 64])), &mut ws.buf_11, &mut buf__stg1_low_band_net_lstm_dec2_lstm_LSTM_output_0_h, &mut buf__stg1_low_band_net_lstm_dec2_lstm_LSTM_output_0_c);
        let _stg1_low_band_net_lstm_dec2_lstm_Transpose_output_0 = lele::kernels::transpose(&_stg1_low_band_net_lstm_dec2_lstm_LSTM_output_0, &[0, 2, 1, 3], &mut ws.buf_7);
        let mut buf__lstm_dec2_lstm_LSTM_output_0_h = Vec::<f32>::new();
        let mut buf__lstm_dec2_lstm_LSTM_output_0_c = Vec::<f32>::new();
        let (_lstm_dec2_lstm_LSTM_output_0, _lstm_dec2_lstm_LSTM_output_1, _lstm_dec2_lstm_LSTM_output_2) = lele::kernels::lstm(&_lstm_dec2_Transpose_output_0, &self.weight_f32(7350800, 262144, &[2, 128, 256]), &self.weight_f32(7612944, 32768, &[2, 128, 32]), Some(&self.weight_f32(7645712, 2048, &[2, 256])), None, Some(&self.weight_f32(7647760, 256, &[2, 1, 32])), Some(&self.weight_f32(7647760, 256, &[2, 1, 32])), &mut ws.buf_8, &mut buf__lstm_dec2_lstm_LSTM_output_0_h, &mut buf__lstm_dec2_lstm_LSTM_output_0_c);
        let _lstm_dec2_lstm_Transpose_output_0 = lele::kernels::transpose(&_lstm_dec2_lstm_LSTM_output_0, &[0, 2, 1, 3], &mut ws.buf_9);
        let _stg1_low_band_net_lstm_dec2_Reshape_output_0 = lele::kernels::reshape(&_stg1_low_band_net_lstm_dec2_lstm_Transpose_output_0, &[-1, 128]);
        let _stg1_low_band_net_lstm_dec2_dense_dense_0_Gemm_output_0 = lele::kernels::gemm(&_stg1_low_band_net_lstm_dec2_Reshape_output_0, &self.weight_f32(7648032, 131072, &[256, 128]), Some(&self.weight_f32(7779104, 1024, &[256])), 1.0, 1.0, false, true, &mut ws.buf_10);
        let _lstm_dec2_Reshape_output_0 = lele::kernels::reshape(&_lstm_dec2_lstm_Transpose_output_0, &[-1, 64]);
        let _stg1_low_band_net_lstm_dec2_dense_dense_1_BatchNormalization_output_0 = lele::kernels::batch_norm(&_stg1_low_band_net_lstm_dec2_dense_dense_0_Gemm_output_0, &self.weight_f32(7780144, 1024, &[256]), &self.weight_f32(7781168, 1024, &[256]), &self.weight_f32(7782192, 1024, &[256]), &self.weight_f32(7783216, 1024, &[256]), 1e-5, &mut ws.buf_11);
        let _lstm_dec2_dense_dense_0_Gemm_output_0 = lele::kernels::gemm(&_lstm_dec2_Reshape_output_0, &self.weight_f32(7784240, 65536, &[256, 64]), Some(&self.weight_f32(7849776, 1024, &[256])), 1.0, 1.0, false, true, &mut ws.buf_12);
        let _stg1_low_band_net_lstm_dec2_dense_dense_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_lstm_dec2_dense_dense_1_BatchNormalization_output_0, &mut ws.buf_8);
        let _lstm_dec2_dense_dense_1_BatchNormalization_output_0 = lele::kernels::batch_norm(&_lstm_dec2_dense_dense_0_Gemm_output_0, &self.weight_f32(7850800, 1024, &[256]), &self.weight_f32(7851824, 1024, &[256]), &self.weight_f32(7852848, 1024, &[256]), &self.weight_f32(7853872, 1024, &[256]), 1e-5, &mut ws.buf_13);
        let _stg1_low_band_net_lstm_dec2_Reshape_1_output_0 = lele::kernels::reshape(&_stg1_low_band_net_lstm_dec2_dense_dense_2_Relu_output_0, &[-1, 1, 1, 256]);
        let _lstm_dec2_dense_dense_2_Relu_output_0 = lele::kernels::relu(&_lstm_dec2_dense_dense_1_BatchNormalization_output_0, &mut ws.buf_7);
        let _stg1_low_band_net_lstm_dec2_Transpose_1_output_0 = lele::kernels::transpose(&_stg1_low_band_net_lstm_dec2_Reshape_1_output_0, &[1, 2, 3, 0], &mut ws.buf_10);
        let _lstm_dec2_Reshape_1_output_0 = lele::kernels::reshape(&_lstm_dec2_dense_dense_2_Relu_output_0, &[-1, 1, 1, 256]);
        let _stg1_low_band_net_Concat_output_0 = lele::kernels::concat(&[&_stg1_low_band_net_dec2_conv1_conv_conv_2_Relu_output_0, &_stg1_low_band_net_lstm_dec2_Transpose_1_output_0], 1, &mut ws.buf_9);
        let _lstm_dec2_Transpose_1_output_0 = lele::kernels::transpose(&_lstm_dec2_Reshape_1_output_0, &[1, 2, 3, 0], &mut ws.buf_11);
        let _stg1_low_band_net_dec1_Resize_output_0 = lele::kernels::resize_nearest(&_stg1_low_band_net_Concat_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_12);
        let _Concat_output_0 = lele::kernels::concat(&[&_dec2_conv1_conv_conv_2_Relu_output_0, &_lstm_dec2_Transpose_1_output_0], 1, &mut ws.buf_13);
        let _stg1_low_band_net_dec1_Concat_output_0 = lele::kernels::concat(&[&_stg1_low_band_net_dec1_Resize_output_0, &_stg1_low_band_net_enc1_conv_conv_2_Relu_output_0], 1, &mut ws.buf_8);
        let _dec1_Resize_output_0 = lele::kernels::resize_nearest(&_Concat_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_14);
        let _stg1_low_band_net_dec1_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_dec1_Concat_output_0, &self.weight_f32(7854896, 28224, &[16, 49, 3, 3]), Some(&self.weight_f32(7883120, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _dec1_Concat_output_0 = lele::kernels::concat(&[&_dec1_Resize_output_0, &_enc1_conv_conv_2_Relu_output_0], 1, &mut ws.buf_7);
        let _stg1_low_band_net_dec1_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_dec1_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_9);
        let _dec1_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_dec1_Concat_output_0, &self.weight_f32(7883184, 7200, &[8, 25, 3, 3]), Some(&self.weight_f32(7890384, 32, &[8])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _stg1_low_band_net_stg1_low_band_net_1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg1_low_band_net_dec1_conv1_conv_conv_2_Relu_output_0, &self.weight_f32(7890416, 512, &[8, 16, 1, 1]), Some(&self.weight_f32(7890928, 32, &[8])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let _dec1_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_dec1_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_10);
        let _stg1_low_band_net_stg1_low_band_net_1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg1_low_band_net_stg1_low_band_net_1_conv_conv_0_Conv_output_0, &mut ws.buf_8);
        let _Concat_3_output_0 = lele::kernels::concat(&[&_Slice_2_output_0, &_dec1_conv1_conv_conv_2_Relu_output_0], 1, &mut ws.buf_6);
        let _Concat_2_output_0 = lele::kernels::concat(&[&_Slice_1_output_0, &_stg1_low_band_net_stg1_low_band_net_1_conv_conv_2_Relu_output_0], 1, &mut ws.buf_3);
        let _Concat_1_output_0 = lele::kernels::concat(&[&_stg1_low_band_net_stg1_low_band_net_1_conv_conv_2_Relu_output_0, &_dec1_conv1_conv_conv_2_Relu_output_0], 2, &mut ws.buf_7);
        let _enc1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_Concat_3_output_0, &self.weight_f32(7890960, 5760, &[16, 10, 3, 3]), Some(&self.weight_f32(7896720, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_9);
        let _stg2_low_band_net_enc1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_Concat_2_output_0, &self.weight_f32(7896784, 11520, &[32, 10, 3, 3]), Some(&self.weight_f32(7908304, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _enc1_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_enc1_conv_conv_0_1_Conv_output_0, &mut ws.buf_5);
        let _stg2_low_band_net_enc1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_enc1_conv_conv_0_Conv_output_0, &mut ws.buf_2);
        let _enc2_conv1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc1_conv_conv_2_1_Relu_output_0, &self.weight_f32(7908432, 18432, &[32, 16, 3, 3]), Some(&self.weight_f32(7926864, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_1);
        let _stg2_low_band_net_enc2_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc1_conv_conv_2_Relu_output_0, &self.weight_f32(7926992, 73728, &[64, 32, 3, 3]), Some(&self.weight_f32(8000720, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_8);
        let _enc2_conv1_conv_conv_2_1_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc2_conv1_conv_conv_0_1_Conv_output_0, 0.01, &mut ws.buf_6);
        let _stg2_low_band_net_enc2_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg2_low_band_net_enc2_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_3);
        let _enc2_conv2_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc2_conv1_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(8000976, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(8037840, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_9);
        let _stg2_low_band_net_enc2_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc2_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(8037968, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(8185424, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _enc2_conv2_conv_conv_2_1_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc2_conv2_conv_conv_0_1_Conv_output_0, 0.01, &mut ws.buf_10);
        let _stg2_low_band_net_enc2_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg2_low_band_net_enc2_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_11);
        let _enc3_conv1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc2_conv2_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(8185680, 73728, &[64, 32, 3, 3]), Some(&self.weight_f32(8259408, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_1);
        let _stg2_low_band_net_enc3_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc2_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(8259664, 294912, &[128, 64, 3, 3]), Some(&self.weight_f32(8554576, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_8);
        let _enc3_conv1_conv_conv_2_1_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc3_conv1_conv_conv_0_1_Conv_output_0, 0.01, &mut ws.buf_6);
        let _stg2_low_band_net_enc3_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg2_low_band_net_enc3_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_3);
        let _enc3_conv2_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc3_conv1_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(8555088, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(8702544, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_9);
        let _stg2_low_band_net_enc3_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc3_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(8702800, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(9292624, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _enc3_conv2_conv_conv_2_1_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc3_conv2_conv_conv_0_1_Conv_output_0, 0.01, &mut ws.buf_12);
        let _stg2_low_band_net_enc3_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg2_low_band_net_enc3_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_13);
        let _enc4_conv1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc3_conv2_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(9293136, 221184, &[96, 64, 3, 3]), Some(&self.weight_f32(9514320, 384, &[96])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_1);
        let _stg2_low_band_net_enc4_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc3_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(9514704, 884736, &[192, 128, 3, 3]), Some(&self.weight_f32(10399440, 768, &[192])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_8);
        let _enc4_conv1_conv_conv_2_1_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc4_conv1_conv_conv_0_1_Conv_output_0, 0.01, &mut ws.buf_6);
        let _stg2_low_band_net_enc4_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg2_low_band_net_enc4_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_3);
        let _enc4_conv2_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc4_conv1_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(10400208, 331776, &[96, 96, 3, 3]), Some(&self.weight_f32(10731984, 384, &[96])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_9);
        let _stg2_low_band_net_enc4_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc4_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(10732368, 1327104, &[192, 192, 3, 3]), Some(&self.weight_f32(12059472, 768, &[192])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _enc4_conv2_conv_conv_2_1_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc4_conv2_conv_conv_0_1_Conv_output_0, 0.01, &mut ws.buf_14);
        let _stg2_low_band_net_enc4_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg2_low_band_net_enc4_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_19);
        let _enc5_conv1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc4_conv2_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(12060240, 442368, &[128, 96, 3, 3]), Some(&self.weight_f32(12502608, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_1);
        let _stg2_low_band_net_enc5_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc4_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(12503120, 1769472, &[256, 192, 3, 3]), Some(&self.weight_f32(14272592, 1024, &[256])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_8);
        let _enc5_conv1_conv_conv_2_1_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc5_conv1_conv_conv_0_1_Conv_output_0, 0.01, &mut ws.buf_6);
        let _stg2_low_band_net_enc5_conv1_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg2_low_band_net_enc5_conv1_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_3);
        let _enc5_conv2_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv1_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(14273616, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(14863440, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_9);
        let _stg2_low_band_net_enc5_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc5_conv1_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(14863952, 2359296, &[256, 256, 3, 3]), Some(&self.weight_f32(17223248, 1024, &[256])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _enc5_conv2_conv_conv_2_1_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc5_conv2_conv_conv_0_1_Conv_output_0, 0.01, &mut ws.buf_20);
        let _stg2_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_stg2_low_band_net_enc5_conv2_conv_conv_0_Conv_output_0, 0.01, &mut ws.buf_21);
        let _aspp_conv1_conv1_0_1_ReduceMean_output_0 = lele::kernels::reduce_mean(&_enc5_conv2_conv_conv_2_1_LeakyRelu_output_0, &[-2], true, &mut ws.buf_1);
        let _aspp_conv2_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(17224272, 65536, &[128, 128, 1, 1]), Some(&self.weight_f32(17289808, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let _aspp_conv3_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(17290320, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(17880144, 512, &[128])), &[4, 2], 1, &[4, 2, 4, 2], &[1, 1], &mut ws.buf_6);
        let _aspp_conv4_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(17880656, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(18470480, 512, &[128])), &[8, 4], 1, &[8, 4, 8, 4], &[1, 1], &mut ws.buf_3);
        let _aspp_conv5_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_1_LeakyRelu_output_0, &self.weight_f32(18470992, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(19060816, 512, &[128])), &[12, 6], 1, &[12, 6, 12, 6], &[1, 1], &mut ws.buf_9);
        let _stg2_low_band_net_aspp_conv1_conv1_0_ReduceMean_output_0 = lele::kernels::reduce_mean(&_stg2_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &[-2], true, &mut ws.buf_4);
        let _stg2_low_band_net_aspp_conv2_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(19061328, 262144, &[256, 256, 1, 1]), Some(&self.weight_f32(19323472, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_22);
        let _stg2_low_band_net_aspp_conv3_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(19324496, 2359296, &[256, 256, 3, 3]), Some(&self.weight_f32(21683792, 1024, &[256])), &[4, 2], 1, &[4, 2, 4, 2], &[1, 1], &mut ws.buf_23);
        let _stg2_low_band_net_aspp_conv4_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(21684816, 2359296, &[256, 256, 3, 3]), Some(&self.weight_f32(24044112, 1024, &[256])), &[8, 4], 1, &[8, 4, 8, 4], &[1, 1], &mut ws.buf_24);
        let _stg2_low_band_net_aspp_conv5_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_enc5_conv2_conv_conv_2_LeakyRelu_output_0, &self.weight_f32(24045136, 2359296, &[256, 256, 3, 3]), Some(&self.weight_f32(26404432, 1024, &[256])), &[12, 6], 1, &[12, 6, 12, 6], &[1, 1], &mut ws.buf_25);
        let _aspp_conv1_conv1_1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_aspp_conv1_conv1_0_1_ReduceMean_output_0, &self.weight_f32(26405456, 65536, &[128, 128, 1, 1]), Some(&self.weight_f32(26470992, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_20);
        let _aspp_conv2_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_aspp_conv2_conv_conv_0_1_Conv_output_0, &mut ws.buf_26);
        let _aspp_conv3_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_aspp_conv3_conv_conv_0_1_Conv_output_0, &mut ws.buf_27);
        let _aspp_conv4_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_aspp_conv4_conv_conv_0_1_Conv_output_0, &mut ws.buf_28);
        let _aspp_conv5_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_aspp_conv5_conv_conv_0_1_Conv_output_0, &mut ws.buf_29);
        let _stg2_low_band_net_aspp_conv1_conv1_1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_aspp_conv1_conv1_0_ReduceMean_output_0, &self.weight_f32(26471504, 262144, &[256, 256, 1, 1]), Some(&self.weight_f32(26733648, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_21);
        let _stg2_low_band_net_aspp_conv2_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_aspp_conv2_conv_conv_0_Conv_output_0, &mut ws.buf_1);
        let _stg2_low_band_net_aspp_conv3_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_aspp_conv3_conv_conv_0_Conv_output_0, &mut ws.buf_8);
        let _stg2_low_band_net_aspp_conv4_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_aspp_conv4_conv_conv_0_Conv_output_0, &mut ws.buf_6);
        let _stg2_low_band_net_aspp_conv5_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_aspp_conv5_conv_conv_0_Conv_output_0, &mut ws.buf_3);
        let _aspp_conv1_conv1_1_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_aspp_conv1_conv1_1_conv_conv_0_1_Conv_output_0, &mut ws.buf_9);
        let _stg2_low_band_net_aspp_conv1_conv1_1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_aspp_conv1_conv1_1_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _aspp_1_Tile_output_0 = lele::kernels::tile(&_aspp_conv1_conv1_1_conv_conv_2_1_Relu_output_0, &[1, 1, 32, 1], &mut ws.buf_22);
        let _stg2_low_band_net_aspp_Tile_output_0 = lele::kernels::tile(&_stg2_low_band_net_aspp_conv1_conv1_1_conv_conv_2_Relu_output_0, &[1, 1, 32, 1], &mut ws.buf_23);
        let _aspp_1_Concat_2_output_0 = lele::kernels::concat(&[&_aspp_1_Tile_output_0, &_aspp_conv2_conv_conv_2_1_Relu_output_0, &_aspp_conv3_conv_conv_2_1_Relu_output_0, &_aspp_conv4_conv_conv_2_1_Relu_output_0, &_aspp_conv5_conv_conv_2_1_Relu_output_0], 1, &mut ws.buf_24);
        let _stg2_low_band_net_aspp_Concat_2_output_0 = lele::kernels::concat(&[&_stg2_low_band_net_aspp_Tile_output_0, &_stg2_low_band_net_aspp_conv2_conv_conv_2_Relu_output_0, &_stg2_low_band_net_aspp_conv3_conv_conv_2_Relu_output_0, &_stg2_low_band_net_aspp_conv4_conv_conv_2_Relu_output_0, &_stg2_low_band_net_aspp_conv5_conv_conv_2_Relu_output_0], 1, &mut ws.buf_25);
        let _aspp_bottleneck_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_aspp_1_Concat_2_output_0, &self.weight_f32(26734672, 327680, &[128, 640, 1, 1]), Some(&self.weight_f32(27062352, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_20);
        let _stg2_low_band_net_aspp_bottleneck_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_aspp_Concat_2_output_0, &self.weight_f32(27062864, 1310720, &[256, 1280, 1, 1]), Some(&self.weight_f32(28373584, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_21);
        let _aspp_bottleneck_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_aspp_bottleneck_conv_conv_0_1_Conv_output_0, &mut ws.buf_9);
        let _stg2_low_band_net_aspp_bottleneck_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_aspp_bottleneck_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _dec4_1_Resize_output_0 = lele::kernels::resize_nearest(&_aspp_bottleneck_conv_conv_2_1_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_22);
        let _stg2_low_band_net_dec4_Resize_output_0 = lele::kernels::resize_nearest(&_stg2_low_band_net_aspp_bottleneck_conv_conv_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_1);
        let _dec4_1_Concat_output_0 = lele::kernels::concat(&[&_dec4_1_Resize_output_0, &_enc4_conv2_conv_conv_2_1_LeakyRelu_output_0], 1, &mut ws.buf_3);
        let _stg2_low_band_net_dec4_Concat_output_0 = lele::kernels::concat(&[&_stg2_low_band_net_dec4_Resize_output_0, &_stg2_low_band_net_enc4_conv2_conv_conv_2_LeakyRelu_output_0], 1, &mut ws.buf_6);
        let _dec4_conv1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_dec4_1_Concat_output_0, &self.weight_f32(28374608, 774144, &[96, 224, 3, 3]), Some(&self.weight_f32(29148752, 384, &[96])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_8);
        let _stg2_low_band_net_dec4_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_dec4_Concat_output_0, &self.weight_f32(29149136, 3096576, &[192, 448, 3, 3]), Some(&self.weight_f32(32245712, 768, &[192])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_20);
        let _dec4_conv1_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_dec4_conv1_conv_conv_0_1_Conv_output_0, &mut ws.buf_9);
        let _stg2_low_band_net_dec4_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_dec4_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _dec3_1_Resize_output_0 = lele::kernels::resize_nearest(&_dec4_conv1_conv_conv_2_1_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_14);
        let _stg2_low_band_net_dec3_Resize_output_0 = lele::kernels::resize_nearest(&_stg2_low_band_net_dec4_conv1_conv_conv_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_1);
        let _dec3_1_Concat_output_0 = lele::kernels::concat(&[&_dec3_1_Resize_output_0, &_enc3_conv2_conv_conv_2_1_LeakyRelu_output_0], 1, &mut ws.buf_3);
        let _stg2_low_band_net_dec3_Concat_output_0 = lele::kernels::concat(&[&_stg2_low_band_net_dec3_Resize_output_0, &_stg2_low_band_net_enc3_conv2_conv_conv_2_LeakyRelu_output_0], 1, &mut ws.buf_6);
        let _dec3_conv1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_dec3_1_Concat_output_0, &self.weight_f32(32246480, 368640, &[64, 160, 3, 3]), Some(&self.weight_f32(32615120, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_8);
        let _stg2_low_band_net_dec3_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_dec3_Concat_output_0, &self.weight_f32(32615376, 1474560, &[128, 320, 3, 3]), Some(&self.weight_f32(34089936, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_19);
        let _dec3_conv1_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_dec3_conv1_conv_conv_0_1_Conv_output_0, &mut ws.buf_9);
        let _stg2_low_band_net_dec3_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_dec3_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _dec2_1_Resize_output_0 = lele::kernels::resize_nearest(&_dec3_conv1_conv_conv_2_1_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_12);
        let _stg2_low_band_net_dec2_Resize_output_0 = lele::kernels::resize_nearest(&_stg2_low_band_net_dec3_conv1_conv_conv_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_1);
        let _dec2_1_Concat_output_0 = lele::kernels::concat(&[&_dec2_1_Resize_output_0, &_enc2_conv2_conv_conv_2_1_LeakyRelu_output_0], 1, &mut ws.buf_3);
        let _stg2_low_band_net_dec2_Concat_output_0 = lele::kernels::concat(&[&_stg2_low_band_net_dec2_Resize_output_0, &_stg2_low_band_net_enc2_conv2_conv_conv_2_LeakyRelu_output_0], 1, &mut ws.buf_6);
        let _dec2_conv1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_dec2_1_Concat_output_0, &self.weight_f32(34090448, 110592, &[32, 96, 3, 3]), Some(&self.weight_f32(34201040, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_8);
        let _stg2_low_band_net_dec2_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_dec2_Concat_output_0, &self.weight_f32(34201168, 442368, &[64, 192, 3, 3]), Some(&self.weight_f32(34643536, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_13);
        let _dec2_conv1_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_dec2_conv1_conv_conv_0_1_Conv_output_0, &mut ws.buf_9);
        let _stg2_low_band_net_dec2_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_dec2_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_4);
        let _lstm_dec2_conv_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_dec2_conv1_conv_conv_2_1_Relu_output_0, &self.weight_f32(34643792, 128, &[1, 32, 1, 1]), Some(&self.weight_f32(34643920, 4, &[1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_10);
        let _stg2_low_band_net_lstm_dec2_conv_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_dec2_conv1_conv_conv_2_Relu_output_0, &self.weight_f32(34643936, 256, &[1, 64, 1, 1]), Some(&self.weight_f32(34644192, 4, &[1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_1);
        let _lstm_dec2_conv_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_lstm_dec2_conv_conv_conv_0_1_Conv_output_0, &mut ws.buf_3);
        let _stg2_low_band_net_lstm_dec2_conv_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_lstm_dec2_conv_conv_conv_0_Conv_output_0, &mut ws.buf_6);
        let _lstm_dec2_1_Gather_3_output_0 = lele::kernels::gather(&_lstm_dec2_conv_conv_conv_2_1_Relu_output_0, &self.weight_i64(0, 8, &[]), 1, &mut ws.buf_8);
        let _stg2_low_band_net_lstm_dec2_Gather_3_output_0 = lele::kernels::gather(&_stg2_low_band_net_lstm_dec2_conv_conv_conv_2_Relu_output_0, &self.weight_i64(0, 8, &[]), 1, &mut ws.buf_11);
        let _lstm_dec2_1_Transpose_output_0 = lele::kernels::transpose(&_lstm_dec2_1_Gather_3_output_0, &[2, 0, 1], &mut ws.buf_12);
        let _stg2_low_band_net_lstm_dec2_Transpose_output_0 = lele::kernels::transpose(&_stg2_low_band_net_lstm_dec2_Gather_3_output_0, &[2, 0, 1], &mut ws.buf_13);
        let mut buf__lstm_dec2_lstm_1_LSTM_output_0_h = Vec::<f32>::new();
        let mut buf__lstm_dec2_lstm_1_LSTM_output_0_c = Vec::<f32>::new();
        let (_lstm_dec2_lstm_1_LSTM_output_0, _lstm_dec2_lstm_1_LSTM_output_1, _lstm_dec2_lstm_1_LSTM_output_2) = lele::kernels::lstm(&_lstm_dec2_1_Transpose_output_0, &self.weight_f32(34644208, 262144, &[2, 128, 256]), &self.weight_f32(34906352, 32768, &[2, 128, 32]), Some(&self.weight_f32(34939120, 2048, &[2, 256])), None, Some(&self.weight_f32(7647760, 256, &[2, 1, 32])), Some(&self.weight_f32(7647760, 256, &[2, 1, 32])), &mut ws.buf_10, &mut buf__lstm_dec2_lstm_1_LSTM_output_0_h, &mut buf__lstm_dec2_lstm_1_LSTM_output_0_c);
        let mut buf__stg2_low_band_net_lstm_dec2_lstm_LSTM_output_0_h = Vec::<f32>::new();
        let mut buf__stg2_low_band_net_lstm_dec2_lstm_LSTM_output_0_c = Vec::<f32>::new();
        let (_stg2_low_band_net_lstm_dec2_lstm_LSTM_output_0, _stg2_low_band_net_lstm_dec2_lstm_LSTM_output_1, _stg2_low_band_net_lstm_dec2_lstm_LSTM_output_2) = lele::kernels::lstm(&_stg2_low_band_net_lstm_dec2_Transpose_output_0, &self.weight_f32(34941168, 524288, &[2, 256, 256]), &self.weight_f32(35465456, 131072, &[2, 256, 64]), Some(&self.weight_f32(35596528, 4096, &[2, 512])), None, Some(&self.weight_f32(7350288, 512, &[2, 1, 64])), Some(&self.weight_f32(7350288, 512, &[2, 1, 64])), &mut ws.buf_1, &mut buf__stg2_low_band_net_lstm_dec2_lstm_LSTM_output_0_h, &mut buf__stg2_low_band_net_lstm_dec2_lstm_LSTM_output_0_c);
        let _lstm_dec2_lstm_1_Transpose_output_0 = lele::kernels::transpose(&_lstm_dec2_lstm_1_LSTM_output_0, &[0, 2, 1, 3], &mut ws.buf_3);
        let _stg2_low_band_net_lstm_dec2_lstm_Transpose_output_0 = lele::kernels::transpose(&_stg2_low_band_net_lstm_dec2_lstm_LSTM_output_0, &[0, 2, 1, 3], &mut ws.buf_6);
        let _lstm_dec2_1_Reshape_output_0 = lele::kernels::reshape(&_lstm_dec2_lstm_1_Transpose_output_0, &[-1, 64]);
        let _stg2_low_band_net_lstm_dec2_Reshape_output_0 = lele::kernels::reshape(&_stg2_low_band_net_lstm_dec2_lstm_Transpose_output_0, &[-1, 128]);
        let _lstm_dec2_dense_dense_0_1_Gemm_output_0 = lele::kernels::gemm(&_lstm_dec2_1_Reshape_output_0, &self.weight_f32(35600624, 65536, &[256, 64]), Some(&self.weight_f32(35666160, 1024, &[256])), 1.0, 1.0, false, true, &mut ws.buf_8);
        let _stg2_low_band_net_lstm_dec2_dense_dense_0_Gemm_output_0 = lele::kernels::gemm(&_stg2_low_band_net_lstm_dec2_Reshape_output_0, &self.weight_f32(35667184, 131072, &[256, 128]), Some(&self.weight_f32(35798256, 1024, &[256])), 1.0, 1.0, false, true, &mut ws.buf_11);
        let _lstm_dec2_dense_dense_1_1_BatchNormalization_output_0 = lele::kernels::batch_norm(&_lstm_dec2_dense_dense_0_1_Gemm_output_0, &self.weight_f32(35799280, 1024, &[256]), &self.weight_f32(35800304, 1024, &[256]), &self.weight_f32(35801328, 1024, &[256]), &self.weight_f32(35802352, 1024, &[256]), 1e-5, &mut ws.buf_10);
        let _stg2_low_band_net_lstm_dec2_dense_dense_1_BatchNormalization_output_0 = lele::kernels::batch_norm(&_stg2_low_band_net_lstm_dec2_dense_dense_0_Gemm_output_0, &self.weight_f32(35803376, 1024, &[256]), &self.weight_f32(35804400, 1024, &[256]), &self.weight_f32(35805424, 1024, &[256]), &self.weight_f32(35806448, 1024, &[256]), 1e-5, &mut ws.buf_1);
        let _lstm_dec2_dense_dense_2_1_Relu_output_0 = lele::kernels::relu(&_lstm_dec2_dense_dense_1_1_BatchNormalization_output_0, &mut ws.buf_12);
        let _stg2_low_band_net_lstm_dec2_dense_dense_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_lstm_dec2_dense_dense_1_BatchNormalization_output_0, &mut ws.buf_13);
        let _lstm_dec2_1_Reshape_1_output_0 = lele::kernels::reshape(&_lstm_dec2_dense_dense_2_1_Relu_output_0, &[-1, 1, 1, 256]);
        let _stg2_low_band_net_lstm_dec2_Reshape_1_output_0 = lele::kernels::reshape(&_stg2_low_band_net_lstm_dec2_dense_dense_2_Relu_output_0, &[-1, 1, 1, 256]);
        let _lstm_dec2_1_Transpose_1_output_0 = lele::kernels::transpose(&_lstm_dec2_1_Reshape_1_output_0, &[1, 2, 3, 0], &mut ws.buf_3);
        let _stg2_low_band_net_lstm_dec2_Transpose_1_output_0 = lele::kernels::transpose(&_stg2_low_band_net_lstm_dec2_Reshape_1_output_0, &[1, 2, 3, 0], &mut ws.buf_6);
        let _Concat_4_output_0 = lele::kernels::concat(&[&_dec2_conv1_conv_conv_2_1_Relu_output_0, &_lstm_dec2_1_Transpose_1_output_0], 1, &mut ws.buf_8);
        let _stg2_low_band_net_Concat_output_0 = lele::kernels::concat(&[&_stg2_low_band_net_dec2_conv1_conv_conv_2_Relu_output_0, &_stg2_low_band_net_lstm_dec2_Transpose_1_output_0], 1, &mut ws.buf_1);
        let _dec1_1_Resize_output_0 = lele::kernels::resize_nearest(&_Concat_4_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_10);
        let _stg2_low_band_net_dec1_Resize_output_0 = lele::kernels::resize_nearest(&_stg2_low_band_net_Concat_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_11);
        let _dec1_1_Concat_output_0 = lele::kernels::concat(&[&_dec1_1_Resize_output_0, &_enc1_conv_conv_2_1_Relu_output_0], 1, &mut ws.buf_12);
        let _stg2_low_band_net_dec1_Concat_output_0 = lele::kernels::concat(&[&_stg2_low_band_net_dec1_Resize_output_0, &_stg2_low_band_net_enc1_conv_conv_2_Relu_output_0], 1, &mut ws.buf_13);
        let _dec1_conv1_conv_conv_0_1_Conv_output_0 = lele::kernels::conv2d(&_dec1_1_Concat_output_0, &self.weight_f32(35807472, 28224, &[16, 49, 3, 3]), Some(&self.weight_f32(35835696, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _stg2_low_band_net_dec1_conv1_conv_conv_0_Conv_output_0 = lele::kernels::conv2d(&_stg2_low_band_net_dec1_Concat_output_0, &self.weight_f32(35835760, 111744, &[32, 97, 3, 3]), Some(&self.weight_f32(35947504, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _dec1_conv1_conv_conv_2_1_Relu_output_0 = lele::kernels::relu(&_dec1_conv1_conv_conv_0_1_Conv_output_0, &mut ws.buf_6);
        let _stg2_low_band_net_dec1_conv1_conv_conv_2_Relu_output_0 = lele::kernels::relu(&_stg2_low_band_net_dec1_conv1_conv_conv_0_Conv_output_0, &mut ws.buf_1);
        let _stg2_low_band_net_stg2_low_band_net_1_conv_conv_2_Relu_output_0 = lele::kernels::conv2d_fused(&_stg2_low_band_net_dec1_conv1_conv_conv_2_Relu_output_0, &self.weight_f32(35947632, 2048, &[16, 32, 1, 1]), Some(&self.weight_f32(35949680, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_2);
        let _Concat_5_output_0 = lele::kernels::concat(&[&_stg2_low_band_net_stg2_low_band_net_1_conv_conv_2_Relu_output_0, &_dec1_conv1_conv_conv_2_1_Relu_output_0], 2, &mut ws.buf_8);
        let _Concat_6_output_0 = lele::kernels::concat(&[&_Slice_output_0, &_Concat_1_output_0, &_Concat_5_output_0], 1, &mut ws.buf_9);
        let _enc1_conv_conv_2_2_Relu_output_0 = lele::kernels::conv2d_fused(&_Concat_6_output_0, &self.weight_f32(35949744, 29952, &[32, 26, 3, 3]), Some(&self.weight_f32(35979696, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], true, &mut ws.buf_4);
        let _enc2_conv1_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc1_conv_conv_2_2_Relu_output_0, &self.weight_f32(35979824, 73728, &[64, 32, 3, 3]), Some(&self.weight_f32(36053552, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_1);
        let _enc2_conv1_conv_conv_2_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc2_conv1_conv_conv_0_2_Conv_output_0, 0.01, &mut ws.buf_5);
        let _enc2_conv2_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc2_conv1_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(36053808, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(36201264, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_2);
        let _enc2_conv2_conv_conv_2_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc2_conv2_conv_conv_0_2_Conv_output_0, 0.01, &mut ws.buf_0);
        let _enc3_conv1_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc2_conv2_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(36201520, 294912, &[128, 64, 3, 3]), Some(&self.weight_f32(36496432, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_6);
        let _enc3_conv1_conv_conv_2_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc3_conv1_conv_conv_0_2_Conv_output_0, 0.01, &mut ws.buf_3);
        let _enc3_conv2_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc3_conv1_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(36496944, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(37086768, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_7);
        let _enc3_conv2_conv_conv_2_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc3_conv2_conv_conv_0_2_Conv_output_0, 0.01, &mut ws.buf_1);
        let _enc4_conv1_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc3_conv2_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(37087280, 884736, &[192, 128, 3, 3]), Some(&self.weight_f32(37972016, 768, &[192])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_5);
        let _enc4_conv1_conv_conv_2_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc4_conv1_conv_conv_0_2_Conv_output_0, 0.01, &mut ws.buf_2);
        let _enc4_conv2_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc4_conv1_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(37972784, 1327104, &[192, 192, 3, 3]), Some(&self.weight_f32(39299888, 768, &[192])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_8);
        let _enc4_conv2_conv_conv_2_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc4_conv2_conv_conv_0_2_Conv_output_0, 0.01, &mut ws.buf_6);
        let _enc5_conv1_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc4_conv2_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(39300656, 1769472, &[256, 192, 3, 3]), Some(&self.weight_f32(41070128, 1024, &[256])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_3);
        let _enc5_conv1_conv_conv_2_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc5_conv1_conv_conv_0_2_Conv_output_0, 0.01, &mut ws.buf_7);
        let _enc5_conv2_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv1_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(41071152, 2359296, &[256, 256, 3, 3]), Some(&self.weight_f32(43430448, 1024, &[256])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_9);
        let _enc5_conv2_conv_conv_2_2_LeakyRelu_output_0 = lele::kernels::leaky_relu(&_enc5_conv2_conv_conv_0_2_Conv_output_0, 0.01, &mut ws.buf_5);
        let _aspp_conv1_conv1_0_2_ReduceMean_output_0 = lele::kernels::reduce_mean(&_enc5_conv2_conv_conv_2_2_LeakyRelu_output_0, &[-2], true, &mut ws.buf_2);
        let _aspp_conv2_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(43431472, 262144, &[256, 256, 1, 1]), Some(&self.weight_f32(43693616, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let _aspp_conv3_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(43694640, 2359296, &[256, 256, 3, 3]), Some(&self.weight_f32(46053936, 1024, &[256])), &[4, 2], 1, &[4, 2, 4, 2], &[1, 1], &mut ws.buf_10);
        let _aspp_conv4_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(46054960, 2359296, &[256, 256, 3, 3]), Some(&self.weight_f32(48414256, 1024, &[256])), &[8, 4], 1, &[8, 4, 8, 4], &[1, 1], &mut ws.buf_3);
        let _aspp_conv5_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_enc5_conv2_conv_conv_2_2_LeakyRelu_output_0, &self.weight_f32(48415280, 2359296, &[256, 256, 3, 3]), Some(&self.weight_f32(50774576, 1024, &[256])), &[12, 6], 1, &[12, 6, 12, 6], &[1, 1], &mut ws.buf_7);
        let _aspp_conv1_conv1_1_conv_conv_0_2_Conv_output_0 = lele::kernels::conv2d(&_aspp_conv1_conv1_0_2_ReduceMean_output_0, &self.weight_f32(50775600, 262144, &[256, 256, 1, 1]), Some(&self.weight_f32(51037744, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_9);
        let _aspp_conv2_conv_conv_2_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv2_conv_conv_0_2_Conv_output_0, &mut ws.buf_11);
        let _aspp_conv3_conv_conv_2_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv3_conv_conv_0_2_Conv_output_0, &mut ws.buf_12);
        let _aspp_conv4_conv_conv_2_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv4_conv_conv_0_2_Conv_output_0, &mut ws.buf_13);
        let _aspp_conv5_conv_conv_2_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv5_conv_conv_0_2_Conv_output_0, &mut ws.buf_22);
        let _aspp_conv1_conv1_1_conv_conv_2_2_Relu_output_0 = lele::kernels::relu(&_aspp_conv1_conv1_1_conv_conv_0_2_Conv_output_0, &mut ws.buf_5);
        let _aspp_2_Tile_output_0 = lele::kernels::tile(&_aspp_conv1_conv1_1_conv_conv_2_2_Relu_output_0, &[1, 1, 64, 1], &mut ws.buf_2);
        let _aspp_2_Concat_2_output_0 = lele::kernels::concat(&[&_aspp_2_Tile_output_0, &_aspp_conv2_conv_conv_2_2_Relu_output_0, &_aspp_conv3_conv_conv_2_2_Relu_output_0, &_aspp_conv4_conv_conv_2_2_Relu_output_0, &_aspp_conv5_conv_conv_2_2_Relu_output_0], 1, &mut ws.buf_8);
        let _aspp_bottleneck_conv_conv_2_2_Relu_output_0 = lele::kernels::conv2d_fused(&_aspp_2_Concat_2_output_0, &self.weight_f32(51038768, 1310720, &[256, 1280, 1, 1]), Some(&self.weight_f32(52349488, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_3);
        let _dec4_2_Resize_output_0 = lele::kernels::resize_nearest(&_aspp_bottleneck_conv_conv_2_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_7);
        let _dec4_2_Concat_output_0 = lele::kernels::concat(&[&_dec4_2_Resize_output_0, &_enc4_conv2_conv_conv_2_2_LeakyRelu_output_0], 1, &mut ws.buf_9);
        let _dec4_conv1_conv_conv_2_2_Relu_output_0 = lele::kernels::conv2d_fused(&_dec4_2_Concat_output_0, &self.weight_f32(52350512, 3096576, &[192, 448, 3, 3]), Some(&self.weight_f32(55447088, 768, &[192])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], true, &mut ws.buf_2);
        let _dec3_2_Resize_output_0 = lele::kernels::resize_nearest(&_dec4_conv1_conv_conv_2_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_8);
        let _dec3_2_Concat_output_0 = lele::kernels::concat(&[&_dec3_2_Resize_output_0, &_enc3_conv2_conv_conv_2_2_LeakyRelu_output_0], 1, &mut ws.buf_10);
        let _dec3_conv1_conv_conv_2_2_Relu_output_0 = lele::kernels::conv2d_fused(&_dec3_2_Concat_output_0, &self.weight_f32(55447856, 1474560, &[128, 320, 3, 3]), Some(&self.weight_f32(56922416, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], true, &mut ws.buf_6);
        let _dec2_2_Resize_output_0 = lele::kernels::resize_nearest(&_dec3_conv1_conv_conv_2_2_Relu_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_7);
        let _dec2_2_Concat_output_0 = lele::kernels::concat(&[&_dec2_2_Resize_output_0, &_enc2_conv2_conv_conv_2_2_LeakyRelu_output_0], 1, &mut ws.buf_5);
        let _dec2_conv1_conv_conv_2_2_Relu_output_0 = lele::kernels::conv2d_fused(&_dec2_2_Concat_output_0, &self.weight_f32(56922928, 442368, &[64, 192, 3, 3]), Some(&self.weight_f32(57365296, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], true, &mut ws.buf_1);
        let _lstm_dec2_conv_conv_conv_2_2_Relu_output_0 = lele::kernels::conv2d_fused(&_dec2_conv1_conv_conv_2_2_Relu_output_0, &self.weight_f32(57365552, 256, &[1, 64, 1, 1]), Some(&self.weight_f32(57365808, 4, &[1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_3);
        let _lstm_dec2_2_Gather_3_output_0 = lele::kernels::gather(&_lstm_dec2_conv_conv_conv_2_2_Relu_output_0, &self.weight_i64(0, 8, &[]), 1, &mut ws.buf_6);
        let _lstm_dec2_2_Transpose_output_0 = lele::kernels::transpose(&_lstm_dec2_2_Gather_3_output_0, &[2, 0, 1], &mut ws.buf_0);
        let mut buf__lstm_dec2_lstm_2_LSTM_output_0_h = Vec::<f32>::new();
        let mut buf__lstm_dec2_lstm_2_LSTM_output_0_c = Vec::<f32>::new();
        let (_lstm_dec2_lstm_2_LSTM_output_0, _lstm_dec2_lstm_2_LSTM_output_1, _lstm_dec2_lstm_2_LSTM_output_2) = lele::kernels::lstm(&_lstm_dec2_2_Transpose_output_0, &self.weight_f32(57365824, 1048576, &[2, 256, 512]), &self.weight_f32(58414400, 131072, &[2, 256, 64]), Some(&self.weight_f32(58545472, 4096, &[2, 512])), None, Some(&self.weight_f32(7350288, 512, &[2, 1, 64])), Some(&self.weight_f32(7350288, 512, &[2, 1, 64])), &mut ws.buf_5, &mut buf__lstm_dec2_lstm_2_LSTM_output_0_h, &mut buf__lstm_dec2_lstm_2_LSTM_output_0_c);
        let _lstm_dec2_lstm_2_Transpose_output_0 = lele::kernels::transpose(&_lstm_dec2_lstm_2_LSTM_output_0, &[0, 2, 1, 3], &mut ws.buf_2);
        let _lstm_dec2_2_Reshape_output_0 = lele::kernels::reshape(&_lstm_dec2_lstm_2_Transpose_output_0, &[-1, 128]);
        let _lstm_dec2_dense_dense_0_2_Gemm_output_0 = lele::kernels::gemm(&_lstm_dec2_2_Reshape_output_0, &self.weight_f32(58549568, 262144, &[512, 128]), Some(&self.weight_f32(58811712, 2048, &[512])), 1.0, 1.0, false, true, &mut ws.buf_8);
        let _lstm_dec2_dense_dense_1_2_BatchNormalization_output_0 = lele::kernels::batch_norm(&_lstm_dec2_dense_dense_0_2_Gemm_output_0, &self.weight_f32(58813760, 2048, &[512]), &self.weight_f32(58815808, 2048, &[512]), &self.weight_f32(58817856, 2048, &[512]), &self.weight_f32(58819904, 2048, &[512]), 1e-5, &mut ws.buf_3);
        let _lstm_dec2_dense_dense_2_2_Relu_output_0 = lele::kernels::relu(&_lstm_dec2_dense_dense_1_2_BatchNormalization_output_0, &mut ws.buf_6);
        let _lstm_dec2_2_Reshape_1_output_0 = lele::kernels::reshape(&_lstm_dec2_dense_dense_2_2_Relu_output_0, &[-1, 1, 1, 512]);
        let _lstm_dec2_2_Transpose_1_output_0 = lele::kernels::transpose(&_lstm_dec2_2_Reshape_1_output_0, &[1, 2, 3, 0], &mut ws.buf_0);
        let _Concat_7_output_0 = lele::kernels::concat(&[&_dec2_conv1_conv_conv_2_2_Relu_output_0, &_lstm_dec2_2_Transpose_1_output_0], 1, &mut ws.buf_5);
        let _dec1_2_Resize_output_0 = lele::kernels::resize_nearest(&_Concat_7_output_0, Some(&self.weight_f32(5122720, 16, &[4]).data), None, "align_corners", &mut ws.buf_2);
        let _dec1_2_Concat_output_0 = lele::kernels::concat(&[&_dec1_2_Resize_output_0, &_enc1_conv_conv_2_2_Relu_output_0], 1, &mut ws.buf_8);
        let _dec1_conv1_conv_conv_2_2_Relu_output_0 = lele::kernels::conv2d_fused(&_dec1_2_Concat_output_0, &self.weight_f32(58821952, 111744, &[32, 97, 3, 3]), Some(&self.weight_f32(58933696, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], true, &mut ws.buf_10);
        let _out_Conv_output_0 = lele::kernels::conv2d(&_dec1_conv1_conv_conv_2_2_Relu_output_0, &self.weight_f32(58933824, 256, &[2, 32, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let _Slice_3_output_0 = lele::kernels::slice(&_out_Conv_output_0, &[0], &[1], &[1], &[1], &mut ws.buf_0);
        let _Slice_4_output_0 = lele::kernels::slice(&_out_Conv_output_0, &[1], &[9223372036854775807], &[1], &[1], &mut ws.buf_1);
        let _Pow_output_0 = lele::kernels::pow(&_Slice_3_output_0, &self.weight_f32(58934080, 4, &[]), &mut ws.buf_2);
        let _Pow_1_output_0 = lele::kernels::pow(&_Slice_4_output_0, &self.weight_f32(58934080, 4, &[]), &mut ws.buf_4);
        let _Add_output_0 = lele::kernels::add(&_Pow_output_0, &_Pow_1_output_0, &mut ws.buf_3);
        let _Add_1_output_0 = lele::kernels::add(&_Add_output_0, &self.weight_f32(58934096, 4, &[]), &mut ws.buf_5);
        let _Sqrt_output_0 = lele::kernels::sqrt(&_Add_1_output_0, &mut ws.buf_8);
        let _Tanh_output_0 = lele::kernels::tanh_kernel(&_Sqrt_output_0, &mut ws.buf_6);
        let _Add_2_output_0 = lele::kernels::add(&_Sqrt_output_0, &self.weight_f32(58934096, 4, &[]), &mut ws.buf_10);
        let _Mul_output_0 = lele::kernels::mul(&_Tanh_output_0, &_Slice_3_output_0, &mut ws.buf_11);
        let _Mul_1_output_0 = lele::kernels::mul(&_Tanh_output_0, &_Slice_4_output_0, &mut ws.buf_2);
        let _Div_1_output_0 = lele::kernels::div(&_Mul_output_0, &_Add_2_output_0, &mut ws.buf_3);
        let _Div_2_output_0 = lele::kernels::div(&_Mul_1_output_0, &_Add_2_output_0, &mut ws.buf_4);
        let _Concat_8_output_0 = lele::kernels::concat(&[&_Div_1_output_0, &_Div_2_output_0], 1, &mut ws.buf_5);
        let output = lele::kernels::pad(&_Concat_8_output_0, &[0, 0, 0, 0, 0, 0, 1, 0], None, "edge", &mut ws.buf_8);
        unsafe { output.detach_or_own() }
    }


    #[cfg(target_arch = "aarch64")]
    fn get_prepared_weight(&self, offset: usize, len: usize, k: usize, n: usize) -> std::sync::Arc<lele::kernels::PreparedWeightsArm> {
        let key = (offset, len);
        {
            let cache = self.prepared_weights_cache.borrow();
            if let Some(pw) = cache.get(&key) {
                return pw.clone();
            }
        }
        let raw_bytes = &self.data[offset..offset+len];
        let pw = std::sync::Arc::new(lele::kernels::prepare_weights_arm(raw_bytes, k, n));
        self.prepared_weights_cache.borrow_mut().insert(key, pw.clone());
        pw
    }
    pub fn weight_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'a, f32> {
        TensorView::from_bytes_f32(&self.data[offset..offset+len], shape)
    }
    pub fn weight_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i32_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i32_as_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i32> {
        TensorView::from_bytes_i32(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i64_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i64_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i32_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i32_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_u8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_u8(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_i8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i8(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_f16(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_f16(&self.data[offset..offset+len], shape.to_vec())
    }
    pub fn weight_u8_raw(&self, offset: usize, len: usize) -> &'a [u8] {
        &self.data[offset..offset+len]
    }

    // Inference Entry Point
    pub fn forward(&self, input: TensorView<'a>) -> TensorView<'static> {
        let mut ws = HNSEPWorkspace::new();
        let res = self.forward_with_workspace(&mut ws, input);
        res.to_owned()
    }
    pub fn forward_with_workspace<'w>(&self, ws: &'w mut HNSEPWorkspace, input: TensorView<'w>) -> TensorView<'w> {
        let (output) = self.run_chunk_0(ws, lele::tensor::TensorView::empty(), input);
        output
    }
}
